/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-05-09 15:32:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import product.model.vo.Product;
import qna.model.vo.QnA;
import notice.model.vo.Notice;
import java.util.ArrayList;
import java.sql.Date;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1589025087189L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1589025088855L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("notice.model.vo.Notice");
    _jspx_imports_classes.add("product.model.vo.Product");
    _jspx_imports_classes.add("qna.model.vo.QnA");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.sql.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");

    	ArrayList<Product> arriProduct = (ArrayList<Product>)request.getAttribute("arriProduct");
    	ArrayList<Product> bestProduct = (ArrayList<Product>)request.getAttribute("bestProduct");
    	ArrayList<Product> closeProduct = (ArrayList<Product>)request.getAttribute("closeProduct");
    	ArrayList<QnA> qnalist = (ArrayList<QnA>)request.getAttribute("qnalist");
    	ArrayList<Notice> noticelist = (ArrayList<Notice>)request.getAttribute("noticelist");
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t\t<title>Insert title here</title>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/action.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/swiper.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\t<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>Insert title here</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/main.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/reset.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/slick/slick.css\"/>\r\n");
      out.write("\t    <!-- Add the new slick-theme.css if you want the default styling -->\r\n");
      out.write("\t    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/slick/slick-theme.css\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("  \t\t  <script src=\"https://kit.fontawesome.com/39b470622c.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/action.js\"></script>\r\n");
      out.write("\t\t<!--script src=\"");
      out.print(request.getContextPath());
      out.write("/js/swiper.min.js\"></script-->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/slick/slick.min.js\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<header id=\"header\">\r\n");
      out.write("\t        <div class=\"menu-wrap\">\r\n");
      out.write("\t            <div class=\"log-menu\">\r\n");
      out.write("\t                <ul class=\"log-sec login\">\r\n");
      out.write("\t                    <li><a href=\"#none\">HELF</a></li>\r\n");
      out.write("\t                    <li><a href=\"#none\">LOGOUT</a></li>\r\n");
      out.write("\t                    <li><a href=\"#none\">MY PAGE</a></li>\r\n");
      out.write("\t                    <li><a href=\"#none\"><i class=\"fas fa-shopping-cart\"></i></a></li>\r\n");
      out.write("\t                </ul>\r\n");
      out.write("\t                <ul class=\"log-sec logout\">\r\n");
      out.write("\t                    <li><a href=\"#none\">HELF</a></li>\r\n");
      out.write("\t                    <li><a href=\"#none\">JOIN</a></li>\r\n");
      out.write("\t                    <li><a href=\"#none\">LOGIN</a></li>\r\n");
      out.write("\t                    <li><a href=\"#none\"><i class=\"fas fa-shopping-cart\"></i></a></li>\r\n");
      out.write("\t                </ul>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div id=\"nav-wrap\">\r\n");
      out.write("\t            <div class=\"logo-wrap\">\r\n");
      out.write("\t                <h1 class=\"logo\"><a href=\"#none\">FUN-THING</a></h1>\r\n");
      out.write("\t                <div class=\"search-box\"><span><i class=\"fas fa-search\"></i></span></div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <nav id=\"nav\">\r\n");
      out.write("\t                <ul>\r\n");
      out.write("\t                    <li>\r\n");
      out.write("\t                        <a href=\"#none\">WOMAN</a>\r\n");
      out.write("\t                        <ul class=\"sub-menu\">\r\n");
      out.write("\t                            <li><a href=\"#none\">OUTER</a></li>\r\n");
      out.write("\t                            <li><a href=\"#none\">TOP</a></li>\r\n");
      out.write("\t                            <li><a href=\"#none\">BOTTOM</a></li>\r\n");
      out.write("\t                            <li><a href=\"#none\">JEAN</a></li>\r\n");
      out.write("\t                            <li><a href=\"#none\">ONEPIECE</a></li>\r\n");
      out.write("\t                        </ul>\r\n");
      out.write("\t                    </li>\r\n");
      out.write("\t                    <li>\r\n");
      out.write("\t                        <a href=\"#none\">MAN</a>\r\n");
      out.write("\t                        <ul class=\"sub-menu\">\r\n");
      out.write("\t                            <li><a href=\"#none\">OUTER</a></li>\r\n");
      out.write("\t                            <li><a href=\"#none\">TOP</a></li>\r\n");
      out.write("\t                            <li><a href=\"#none\">BOTTOM</a></li>\r\n");
      out.write("\t                            <li><a href=\"#none\">JEAN</a></li>\r\n");
      out.write("\t                        </ul>\r\n");
      out.write("\t                    </li>\r\n");
      out.write("\t                    <li><a href=\"#none\">CALENDAR</a></li>\r\n");
      out.write("\t                </ul>\r\n");
      out.write("\t            </nav>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <!-- nav end -->\r\n");
      out.write("\t    </header>\r\n");
      out.write("\t</body>\r\n");
      out.write("\t \r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//헤더 상단 고정\r\n");
      out.write("\t\tvar headerTop = $(\"#header\").offset();\r\n");
      out.write("\t\tconsole.log(headerTop);\r\n");
      out.write("\t\t$(window).scroll(function(){\r\n");
      out.write("\t\t  if($(document).scrollTop() > headerTop.top){\r\n");
      out.write("\t\t    $(\"#header\").addClass(\"fixed\");\r\n");
      out.write("\t\t  }else{\r\n");
      out.write("\t\t    $(\"#header\").removeClass(\"fixed\");\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 검색창 클릭 시\r\n");
      out.write("\t\t$(\".search-box\").click(function(){\r\n");
      out.write("\t\t    $(\".searchWrap\").show();\r\n");
      out.write("\t\t    $('html').css({'overflow': 'hidden', 'height': '100%'});\r\n");
      out.write("\t\t    $('#element').on('scroll touchmove mousewheel', function(event) {\r\n");
      out.write("\t\t      event.preventDefault();\r\n");
      out.write("\t\t      event.stopPropagation();\r\n");
      out.write("\t\t      return false;\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 검색창 열렸을 때 닫기\r\n");
      out.write("\t\t$(\".searchWrap .close\").click(function(){\r\n");
      out.write("\t\t  $(\".searchWrap\").hide();\r\n");
      out.write("\t\t  $('html').css({'overflow': 'scroll', 'height': '100%'});\r\n");
      out.write("\t\t  $('#element').off('scroll touchmove mousewheel');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//nav menu\r\n");
      out.write("\t\t$(\"#nav > ul > li .sub-menu\").hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#nav > ul > li\").hover(function(){\r\n");
      out.write("\t\t  $(this).children(\".sub-menu\").stop().slideDown();\r\n");
      out.write("\t\t}, function(){\r\n");
      out.write("\t\t  $(this).children(\".sub-menu\").stop().slideUp();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"searchWrap\">\r\n");
      out.write("\t        <form id=\"search\" action=\"#\" method=\"post\">\r\n");
      out.write("\t            <input type=\"text\" id=\"search\" name=\"search\" /><i class=\"fas fa-search\"></i>\r\n");
      out.write("\t        </form>\r\n");
      out.write("\t        <div class=\"close\"><i class=\"fas fa-times\"></i></div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <!-- search end -->\r\n");
      out.write("\t    <div id=\"container\">\r\n");
      out.write("\t        <div id=\"content\">\r\n");
      out.write("\t            <div class=\"main-img\">\r\n");
      out.write("\t                <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/main_img.jpg\" />\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div class=\"con-box discover\">\r\n");
      out.write("\t                <h2>DISCOVER THE LATEST ARRIVALS</h2>\r\n");
      out.write("\t                <ul class=\"product\">\r\n");
      out.write("\t                \r\n");
      out.write("\t                \t");
if(arriProduct != null) { 
      out.write("\r\n");
      out.write("\t                \t");
	for(int i = 0; i<8; i++) { 
      out.write("\r\n");
      out.write("\t                \t");
		Product p = arriProduct.get(i);
	                	
	                			String thumbnail = p.getThumbnail();
	                			String pName = p.getpName();
	                			Date fStartDate = p.getfStartDate();
	                			Date fEndDate = p.getfEndDate();
	                			
	                			String thumbnailUrl = "web/images/thumbnail/" + thumbnail + ".jsp";
	                	
      out.write("\r\n");
      out.write("\t\t                    <li>\r\n");
      out.write("\t\t                        <div class=\"prod-img\">\r\n");
      out.write("\t\t                            ");
      out.write("\r\n");
      out.write("\t\t                            <a href=\"#none\"><img src=\"");
      out.print(request.getContextPath()+"/images/thumbnail/" + thumbnail + ".jpg" );
      out.write("\"></a>\r\n");
      out.write("\t\t                            ");
      out.write("\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                        <ul class=\"prod-cont\">\r\n");
      out.write("\t\t                            <!-- <li class=\"prod-brand\">brand</li> -->\r\n");
      out.write("\t\t                            <li class=\"prod-tit\"><a href=\"#none\">");
      out.print(pName );
      out.write("</a></li>\r\n");
      out.write("\t\t                            <li class=\"fun-sdate\">");
      out.print(fStartDate );
      out.write('~');
      out.print(fEndDate );
      out.write("</li>\r\n");
      out.write("\t\t                        </ul>\r\n");
      out.write("\t\t                    </li>\r\n");
      out.write("\t                    ");
} 
	                	}else { 
      out.write("\r\n");
      out.write("\t\t                    <li>\r\n");
      out.write("\t\t                        <div class=\"prod-img\">\r\n");
      out.write("\t\t                            <a href=\"#none\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/thumbnail/thumb001.jpg\"></a>\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                        <ul class=\"prod-cont\">\r\n");
      out.write("\t\t                            <li class=\"prod-brand\">brand</li>\r\n");
      out.write("\t\t                            <li class=\"prod-tit\"><a href=\"#none\">product title</a></li>\r\n");
      out.write("\t\t                            <li class=\"fun-sdate\">2020/05/30~</li>\r\n");
      out.write("\t\t                        </ul>\r\n");
      out.write("\t\t                    </li>\r\n");
      out.write("\t                    ");
} 
      out.write("\r\n");
      out.write("\t                    \r\n");
      out.write("\t                </ul>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <!-- discover end -->\r\n");
      out.write("\t\r\n");
      out.write("            <div class=\"best-sell\">\r\n");
      out.write("                <h2>BEST SELLING</h2>\r\n");
      out.write("                <section id=\"features\" class=\"blue\">\r\n");
      out.write("                    <div class=\"slider center\">\r\n");
      out.write("                    \t");
if(bestProduct != null) { 
      out.write("\r\n");
      out.write("                    \t");
	for(int i=0; i<6;i++) { 
      out.write("\r\n");
      out.write("                    \t");
		 Product p = bestProduct.get(i);
	                			
								 String thumbnail = p.getThumbnail();
								 String pName = p.getpName();
								 Date fStartDate = p.getfStartDate();
								 Date fEndDate = p.getfEndDate();
						
      out.write("\r\n");
      out.write("\t\t                        <div>\r\n");
      out.write("\t\t                            <img src=\"");
      out.print(request.getContextPath()+"/images/thumbnail/" + thumbnail + ".jpg" );
      out.write("\">\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t                   ");
	} 
      out.write("\r\n");
      out.write("                       ");
}else { 
      out.write("\r\n");
      out.write("                       \r\n");
      out.write("                       ");
} 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("\t            <div class=\"con-box completion\">\r\n");
      out.write("\t                <h2>CLOSE TO COMPLETION</h2>\r\n");
      out.write("\t                <ul class=\"product\">\r\n");
      out.write("\t                \t");
if(closeProduct != null) { 
      out.write("\r\n");
      out.write("\t                \t");
	for(int i = 0; i<8; i++) { 
      out.write("\r\n");
      out.write("\t                \t");
		Product p = closeProduct.get(i);
	                			
			                	String thumbnail = p.getThumbnail();
		            			String pName = p.getpName();
		            			Date fStartDate = p.getfStartDate();
		            			Date fEndDate = p.getfEndDate();
	                	
      out.write("\r\n");
      out.write("\t                    <li>\r\n");
      out.write("\t                        <div class=\"prod-img\">\r\n");
      out.write("\t                            <a href=\"#none\"><img src=\"");
      out.print(request.getContextPath()+"/images/thumbnail/" + thumbnail + ".jpg" );
      out.write("\"></a>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                        <ul class=\"prod-cont\">\r\n");
      out.write("\t                            <!-- <li class=\"prod-brand\">brand</li> -->\r\n");
      out.write("\t                            <li class=\"prod-tit\"><a href=\"#none\">");
      out.print(pName );
      out.write("</a></li>\r\n");
      out.write("\t                            <li class=\"fun-sdate\">");
      out.print(fStartDate );
      out.write('~');
      out.print(fEndDate );
      out.write("</li>\r\n");
      out.write("\t                        </ul>\r\n");
      out.write("\t                    </li>\r\n");
      out.write("\t                    \r\n");
      out.write("\t                    ");
	} 
      out.write("\r\n");
      out.write("\t                    ");
}else{ 
      out.write("\r\n");
      out.write("\t                    \r\n");
      out.write("\t                    ");
} 
      out.write("\r\n");
      out.write("\t                </ul>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <!-- completion end -->\r\n");
      out.write("\t\r\n");
      out.write("\t        <!-- sell content end -->\r\n");
      out.write("\t        <div class=\"bt-wrap\">\r\n");
      out.write("\t            <div class=\"bt-sec left\">\r\n");
      out.write("\t                <h3>QNA</h3>\r\n");
      out.write("\t                <ul>\r\n");
      out.write("\t                \t");
if(qnalist != null) { 
      out.write("\r\n");
      out.write("\t                \t");
	for(int i =0; i<4; i++) { 
      out.write("\r\n");
      out.write("\t                \t");
		QnA q = qnalist.get(i);
	                			
	                			String title = q.getQnaTitle();
	                			Date qnaDate = q.getQnaDate();
	                	
      out.write("\r\n");
      out.write("\t                    \t\t<li><a href=\"#none\">");
      out.print(title );
      out.write("</a><span>");
      out.print(qnaDate );
      out.write("</span></li>\r\n");
      out.write("\t                    ");
	} 
      out.write("\r\n");
      out.write("\t                    ");
}else{} 
      out.write("\r\n");
      out.write("\t                </ul>\r\n");
      out.write("\t            </div><!-- left end -->\r\n");
      out.write("\t            \r\n");
      out.write("\t            <div class=\"bt-sec bcenter\">\r\n");
      out.write("\t                <h3>NOTICE</h3>\r\n");
      out.write("\t                <ul>\r\n");
      out.write("\t                \t");
if(noticelist != null) { 
      out.write("\r\n");
      out.write("\t                \t");
	for(int i=0;i<4;i++) { 
      out.write("\r\n");
      out.write("\t                \t");
		Notice n = noticelist.get(i);
	                			
	                			String title = n.getnTitle();
	                			Date date = n.getnDate();
	                	
      out.write("\r\n");
      out.write("\t                    \t<li><a href=\"#none\">");
      out.print(title );
      out.write("</a><span>");
      out.print(date );
      out.write("</span></li>\r\n");
      out.write("\t                    \r\n");
      out.write("\t                    ");
	} 
      out.write("\r\n");
      out.write("\t                    ");
} else {} 
      out.write("\r\n");
      out.write("\t                </ul>\r\n");
      out.write("\t            </div><!-- center end -->\r\n");
      out.write("\t            \r\n");
      out.write("\t            <div class=\"bt-sec right\">\r\n");
      out.write("\t                <h3>CUSTEMER CENTER</h3>\r\n");
      out.write("\t                <ul>\r\n");
      out.write("\t                    <li class=\"tel\">1234-5678</li>\r\n");
      out.write("\t                    <li>운영시간 : 10:00 ~ 17:00</li>\r\n");
      out.write("\t                    <li>점심시간 : 11:30 ~ 13:30</li>\r\n");
      out.write("\t                    <li>주말 및 공휴일은 휴무입니다.</li>\r\n");
      out.write("\t                </ul>\r\n");
      out.write("\t            </div><!-- right end -->\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t\r\n");
      out.write("\t        </div><!-- content end -->\r\n");
      out.write("\t    </div><!-- container end -->\r\n");
      out.write("\t    \r\n");
      out.write("\t    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<footer id=\"footer\">\r\n");
      out.write("\t        <div class=\"footer-wrap\">\r\n");
      out.write("\t            <div class=\"ft-top\">\r\n");
      out.write("\t                <ul>\r\n");
      out.write("\t                    <li><a href=\"#none\">고객센터</a></li>\r\n");
      out.write("\t                    <li><a href=\"#none\">서비스이용약관</a></li>\r\n");
      out.write("\t                    <li><a href=\"#none\"><b>개인정보취급방침</b></a></li>\r\n");
      out.write("\t                    <li><a href=\"#none\">이용안내</a></li>\r\n");
      out.write("\t                    <li><a href=\"#none\">광고/제휴문의</a></li>\r\n");
      out.write("\t                    <li><a href=\"#none\">사업자정보확인</a></li>\r\n");
      out.write("\t                </ul>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div class=\"ft-bottom\">\r\n");
      out.write("\t                <p class=\"ft-logo\">FUN-THING</p>\r\n");
      out.write("\t                <div class=\"ft-cont\">\r\n");
      out.write("\t                    <span>(주)볼빨간조</span><span>대표 : 최상원</span><span>서울 강남구 테헤란로14길 6 남도빌딩 2층 B Class</span><span>통신판매업 신고번호 : 신고 준비중</span><br/>\r\n");
      out.write("\t                    <span>사업자번호 : 123-77-4567</span><span>개인정보관리책임자 : 조한솔</span><span>고객센터 대표전화 : 1234-5678</span><span>이메일 : rngus3698@naver.com</span>\r\n");
      out.write("\t                    <p class=\"copyright\">COPYRIGHTS 2020 FUNTHING. ALL RIGHTS RESERVED</p>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </footer>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t    $('.center').slick({\r\n");
      out.write("\t    centerMode: true,\r\n");
      out.write("\t    centerPadding: '200px',\r\n");
      out.write("\t    infinite : true, \t//무한 반복 옵션\t \r\n");
      out.write("\t    slidesToShow : 3,\t\t// 한 화면에 보여질 컨텐츠 개수\r\n");
      out.write("\t    slidesToScroll : 1,\t\t//스크롤 한번에 움직일 컨텐츠 개수\r\n");
      out.write("\t    speed : 100,\t // 다음 버튼 누르고 다음 화면 뜨는데까지 걸리는 시간(ms)\r\n");
      out.write("\t    arrows : true, \t\t// 옆으로 이동하는 화살표 표시 여부\r\n");
      out.write("\t    dots : true, \t\t// 스크롤바 아래 점으로 페이지네이션 여부\r\n");
      out.write("\t    autoplay : true,\t\t\t// 자동 스크롤 사용 여부\r\n");
      out.write("\t    autoplaySpeed : 5000, \t\t// 자동 스크롤 시 다음으로 넘어가는데 걸리는 시간 (ms)\r\n");
      out.write("\t    pauseOnHover : true,\t\t// 슬라이드 이동\t시 마우스 호버하면 슬라이더 멈추게 설정\r\n");
      out.write("\t    // prevArrow : \"<button type='button' class='slick-prev'>Previous</button>\",\t\t// 이전 화살표 모양 설정\r\n");
      out.write("\t    // nextArrow : \"<button type='button' class='slick-next'>Next</button>\",\t\t// 다음 화살표 모양 설정\r\n");
      out.write("\t    dotsClass : \"slick-dots\", \t//아래 나오는 페이지네이션(점) css class 지정\r\n");
      out.write("\t    draggable : true, \t//드래그 가능 여부 \r\n");
      out.write("\t    responsive: [\r\n");
      out.write("\t        {\r\n");
      out.write("\t        breakpoint: 768,\r\n");
      out.write("\t        settings: {\r\n");
      out.write("\t            arrows: false,\r\n");
      out.write("\t            centerMode: true,\r\n");
      out.write("\t            centerPadding: '40px',\r\n");
      out.write("\t            slidesToShow: 3\r\n");
      out.write("\t        }\r\n");
      out.write("\t        },\r\n");
      out.write("\t        {\r\n");
      out.write("\t        breakpoint: 480,\r\n");
      out.write("\t        settings: {\r\n");
      out.write("\t            arrows: false,\r\n");
      out.write("\t            centerMode: true,\r\n");
      out.write("\t            centerPadding: '40px',\r\n");
      out.write("\t            slidesToShow: 1\r\n");
      out.write("\t        }\r\n");
      out.write("\t        }\r\n");
      out.write("\t    ]\r\n");
      out.write("\t    });\r\n");
      out.write("\t</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
