/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-05-17 12:05:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class productDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/product/../common/header.jsp", Long.valueOf(1589711471208L));
    _jspx_dependants.put("/views/product/../common/footer.jsp", Long.valueOf(1589501099800L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title></title>\r\n");
      out.write("    <!-- <script src=\"../js/jQuery-3.4.1.min.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/39b470622c.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("        body {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            font-family:  'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ul {\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            padding:5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #brand{\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            color:#30586e;\r\n");
      out.write("        }\r\n");
      out.write("        #name{\r\n");
      out.write("            padding-bottom: 5px;\r\n");
      out.write("             border-bottom: 1.5px solid #30586e;\r\n");
      out.write("        }\r\n");
      out.write("        #product_description{\r\n");
      out.write("            font-size:small;\r\n");
      out.write("        }\r\n");
      out.write("        #prod-detail {\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #prod-detail:after {\r\n");
      out.write("            content: \"\";\r\n");
      out.write("            clear: both;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #photo {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 30%;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #photo_area {\r\n");
      out.write("            float: left;\r\n");
      out.write("            width: 30%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #p_detalis {\r\n");
      out.write("            float: left;\r\n");
      out.write("            width: 50%;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            padding: 0 0 0 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #right_wrap {}\r\n");
      out.write("\r\n");
      out.write("        #right_wrap:after {\r\n");
      out.write("            content: \"\";\r\n");
      out.write("            clear: both;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #right_wrap ul {}\r\n");
      out.write("\r\n");
      out.write("        #right_wrap ul li {}\r\n");
      out.write("\r\n");
      out.write("        #right_wrap ul li:after {\r\n");
      out.write("            content: \"\";\r\n");
      out.write("            clear: both;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #right_wrap ul li .price_left {\r\n");
      out.write("            float: left;\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #right_wrap ul li .price_right {\r\n");
      out.write("            float: right;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .price {\r\n");
      out.write("            float: left;\r\n");
      out.write("            width: 40%;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            padding-right: 5%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .buy_information {\r\n");
      out.write("            float: left;\r\n");
      out.write("            width: 50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .price_dis{\r\n");
      out.write("            color:red;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #color{\r\n");
      out.write("            width: 250px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #num{\r\n");
      out.write("            width: 245px;\r\n");
      out.write("            height: 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #by_now, #shopping_bag{\r\n");
      out.write("            background:#9fa5a8;\r\n");
      out.write("            color:white;\r\n");
      out.write("            border:0;\r\n");
      out.write("            width:130px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 내비게이션 시작 */\r\n");
      out.write("        #section{margin: auto; width: 80%; height: 100%;}\r\n");
      out.write("        .sec_nav{margin: 0; width: 100%; height: 80px; background-color: rgb(223, 220, 220); text-align:center;}\r\n");
      out.write("\r\n");
      out.write("        .sec_nav ul {height: 100%; line-height: 80px; margin:0 auto; display:inline-block; }\r\n");
      out.write("        .sec_nav ul:after { clear:both; content:\"\"; display:block; }\r\n");
      out.write("        .sec_nav ul li {list-style: none; float: left; box-sizing:border-box; padding:0;}\r\n");
      out.write("        .sec_nav ul li a{text-decoration: none; margin-left: 100px; margin-right: 100px; color: black;}\r\n");
      out.write("\r\n");
      out.write("        .sec_nav .sel_point { background:#0f4a7e; }\r\n");
      out.write("        .sec_nav .sel_point a { display:inline-block; color:#fff; }\r\n");
      out.write("\r\n");
      out.write("        #details_area{margin: auto; width: 100%; text-align:center; }\r\n");
      out.write("\r\n");
      out.write("        #review_area{height: auto; width: 100%; /*border: 1px solid gray;*/ padding-bottom:40px; }\r\n");
      out.write("        #review_area .rev_rate  { width:100%; margin:20px 0 0; }\r\n");
      out.write("        #review_area .rev_rate select { width:100%; font-size:24px; height:50px; }\r\n");
      out.write("        #review_area .rev_textArea { box-sizing:border-box; margin: 20px 0 20px;  }\r\n");
      out.write("        #review_area .rev_textArea textarea { width:100%; resize: none; padding:10px; box-sizing:border-box; }\r\n");
      out.write("        #review_area .rev_textArea textarea::placeholder { color:#666; }\r\n");
      out.write("        #review_area .rev_btns { width:100%; }\r\n");
      out.write("        #review_area .rev_btns:after { display:block; content:\"\"; clear:both; }\r\n");
      out.write("        #review_area .rev_btns .rev_submit { float:right; width:160px; border-radius:0; height:60px; background:#30586e; color:#fff; font-size:16px; border:none; }\r\n");
      out.write("        #review_area .rev_btns .fileWrap { float:left; margin:0; width:60px; height:60px; overflow:hidden; position:relative; }\r\n");
      out.write("        #review_area .rev_btns .fileWrap input { font-size:40px; opacity:0; position:relative; z-index:2; }\r\n");
      out.write("        #review_area .rev_btns .fileWrap span { position:absolute; top:0; left:0; }\r\n");
      out.write("        #review_area .rev_btns .fileWrap span i { color:#30586e; font-size:60px; }\r\n");
      out.write("\r\n");
      out.write("        #QnA_area h3{float: left;}\r\n");
      out.write("        #QnA_area button{float: right; background-color: #30586e; border: 0px; height: 60px; color: white; font-size: 100%;}\r\n");
      out.write("        #QnA_area table{border-top: 2px solid rgb(223, 220, 220); border-bottom: 1px solid rgb(223, 220, 220); width: 100%;}\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    ");

    	Member loginUser = (Member)session.getAttribute("loginUser");
    
      out.write(" \n");
      out.write("<!DOCTYPE html>\n");
      out.write("\t<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\n");
      out.write("\t\t<meta charset=\"UTF-8\">\n");
      out.write("\t\t<title>Insert title here</title>\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/main.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/reset.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\">\n");
      out.write("\t    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/slick/slick.css\"/>\n");
      out.write("\t    <!-- Add the new slick-theme.css if you want the default styling -->\n");
      out.write("\t    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/slick/slick-theme.css\"/>\n");
      out.write("\t\t\n");
      out.write("  \t\t  <script src=\"https://kit.fontawesome.com/39b470622c.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("\t\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/action.js\"></script>\n");
      out.write("\t\t<!--script src=\"");
      out.print(request.getContextPath());
      out.write("/js/swiper.min.js\"></script-->\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/slick/slick.min.js\"></script>\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t\t<header id=\"header\">\n");
      out.write("\t        <div class=\"menu-wrap\">\n");
      out.write("\t            <div class=\"log-menu\">\n");
      out.write("\t            \n");
      out.write("\t            ");
 if(loginUser != null){ 
      out.write("\n");
      out.write("\t                <ul class=\"log-sec login\">\n");
      out.write("\t                ");
if(loginUser.getmId().equals("master")){ 
      out.write("\n");
      out.write("\t                \t<li class=\"master\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/mainView\">MASTER</a></li>\n");
      out.write("\t                \t");
} 
      out.write("\n");
      out.write("\t                    <li><a href=\"#none\">HELP</a></li>\n");
      out.write("\t                    <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/logout.me\">LOGOUT</a></li>\n");
      out.write("\t                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/member/myPageMain.jsp\">MY PAGE</a></li>\n");
      out.write("\t                    <li><a href=\"#none\"><i class=\"fas fa-shopping-cart\"></i></a></li>\n");
      out.write("\t                </ul>\n");
      out.write("\t                ");
 }else{ 
      out.write("\n");
      out.write("\t                <ul class=\"log-sec logout\">\n");
      out.write("\t                    <li><a href=\"#none\">HELP</a></li>\n");
      out.write("\t                    <li><a href=\"#none\">JOIN</a></li>\n");
      out.write("\t                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/member/memberLogin.jsp\">LOGIN</a></li>\n");
      out.write("\t                    <li><a href=\"#none\"><i class=\"fas fa-shopping-cart\"></i></a></li>\n");
      out.write("\t                </ul>\n");
      out.write("\t                ");
 } 
      out.write("\n");
      out.write("\t                \n");
      out.write("\t            </div>\n");
      out.write("\t        </div>\n");
      out.write("\t        <div id=\"nav-wrap\">\n");
      out.write("\t            <div class=\"logo-wrap\">\n");
      out.write("\t                <h1 class=\"logo\"><a href=\"index.jsp\">FUN-THING</a></h1>\n");
      out.write("\t                \n");
      out.write("\t                <div class=\"search-box\"><span><i class=\"fas fa-search\"></i></span></div>\n");
      out.write("\t                \n");
      out.write("\t            </div>\n");
      out.write("\t            <nav id=\"nav\">\n");
      out.write("\t                <ul>\n");
      out.write("\t                    <li>\n");
      out.write("\t                        <a href=\"#none\">WOMAN</a>\n");
      out.write("\t                        <ul class=\"sub-menu\">\n");
      out.write("\t                            <li><a href=\"#none\">OUTER</a></li>\n");
      out.write("\t                            <li><a href=\"#none\">TOP</a></li>\n");
      out.write("\t                            <li><a href=\"#none\">BOTTOM</a></li>\n");
      out.write("\t                            <li><a href=\"#none\">JEAN</a></li>\n");
      out.write("\t                            <li><a href=\"#none\">ONEPIECE</a></li>\n");
      out.write("\t                        </ul>\n");
      out.write("\t                    </li>\n");
      out.write("\t                    <li>\n");
      out.write("\t                        <a href=\"#none\">MAN</a>\n");
      out.write("\t                        <ul class=\"sub-menu\">\n");
      out.write("\t                            <li><a href=\"#none\">OUTER</a></li>\n");
      out.write("\t                            <li><a href=\"#none\">TOP</a></li>\n");
      out.write("\t                            <li><a href=\"#none\">BOTTOM</a></li>\n");
      out.write("\t                            <li><a href=\"#none\">JEAN</a></li>\n");
      out.write("\t                        </ul>\n");
      out.write("\t                    </li>\n");
      out.write("\t                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/CalendarSelect\">CALENDAR</a></li>\n");
      out.write("\t                </ul>\n");
      out.write("\t            </nav>\n");
      out.write("\t        </div>\n");
      out.write("\t        <!-- nav end -->\n");
      out.write("\t    </header>\n");
      out.write("\t    \n");
      out.write("\t    <div class=\"searchWrap\">\n");
      out.write("\t        <form id=\"search\" action=\"");
      out.print(request.getContextPath() );
      out.write("/MainSearch\" method=\"GET\">\n");
      out.write("\t        \n");
      out.write("\t            <input type=\"text\" id=\"search\" name=\"search\" /><button type=\"submit\" id=\"submitBtn\" style=\"background-color:transparent; border:0px;\"><i class=\"fas fa-search\"></i></button>\n");
      out.write("\t        </form>\n");
      out.write("\t        <div class=\"close\"><i class=\"fas fa-times\"></i></div>\n");
      out.write("\t    </div>\n");
      out.write("\t</body>\n");
      out.write("\t \n");
      out.write("\t<script>\n");
      out.write("\t\t//헤더 상단 고정\n");
      out.write("\t\tvar headerTop = $(\"#header\").offset();\n");
      out.write("\t\tconsole.log(headerTop);\n");
      out.write("\t\t$(window).scroll(function(){\n");
      out.write("\t\t  if($(document).scrollTop() > headerTop.top){\n");
      out.write("\t\t    $(\"#header\").addClass(\"fixed\");\n");
      out.write("\t\t  }else{\n");
      out.write("\t\t    $(\"#header\").removeClass(\"fixed\");\n");
      out.write("\t\t  }\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t// 검색창 클릭 시\n");
      out.write("\t\t$(\".search-box\").click(function(){\n");
      out.write("\t\t    $(\".searchWrap\").show();\n");
      out.write("\t\t    $('html').css({'overflow': 'hidden', 'height': '100%'});\n");
      out.write("\t\t    $('#element').on('scroll touchmove mousewheel', function(event) {\n");
      out.write("\t\t      event.preventDefault();\n");
      out.write("\t\t      event.stopPropagation();\n");
      out.write("\t\t      return false;\n");
      out.write("\t\t    });\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t// 검색창 열렸을 때 닫기\n");
      out.write("\t\t$(\".searchWrap .close\").click(function(){\n");
      out.write("\t\t  $(\".searchWrap\").hide();\n");
      out.write("\t\t  $('html').css({'overflow': 'scroll', 'height': '100%'});\n");
      out.write("\t\t  $('#element').off('scroll touchmove mousewheel');\n");
      out.write("\t\t\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t//nav menu\n");
      out.write("\t\t$(\"#nav > ul > li .sub-menu\").hide();\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"#nav > ul > li\").hover(function(){\n");
      out.write("\t\t  $(this).children(\".sub-menu\").stop().slideDown();\n");
      out.write("\t\t}, function(){\n");
      out.write("\t\t  $(this).children(\".sub-menu\").stop().slideUp();\n");
      out.write("\t\t\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"prod-detail\">\r\n");
      out.write("        <!-- 상품 정보 -->\r\n");
      out.write("        <div id=\"detail_top\">\r\n");
      out.write("            <div id=\"photo_area\">\r\n");
      out.write("                <img id=\"photo\" name=\"photo\" src=\"images/thumbnail/thumb001.jpg\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"p_detalis\" name=\"p_detalis\">\r\n");
      out.write("                <ul id=\"product_ul\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div id=\"brand\" name=\"brand\">OFT</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div id=\"name\" name=\"name\">V NECK BEAN BUTTON ONEPIECE_2COLORS</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div id=\"product_description\">\r\n");
      out.write("                            힙을 덮지 않는 길이감으로 데님, 스커트에 매치해도 잘 어울립니다.\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("                <!-- 상품 판매가 -->\r\n");
      out.write("                <div id=\"right_wrap\">\r\n");
      out.write("                    <ul class=\"price\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"price_left\">정상가</span><span class=\"price_right\"><s>140,700</s></span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"price_left\">판매가</span><span class=\"price_right\"><span\r\n");
      out.write("                                    class=\"price_dis\">5%▼</span> 139,500</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"price_left\">적립금</span><span class=\"price_right\">6,975p</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"price_left\">회원가</span><span class=\"price_right\"><span\r\n");
      out.write("                                    class=\"price_dis\">15%▼</span> 118,575</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                    <!-- 상품 선택 및 구매/장바구니 -->\r\n");
      out.write("                    <div class=\"buy_information\">\r\n");
      out.write("                        <form>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <select id=\"color\">\r\n");
      out.write("                                        <option>size 선택</option>\r\n");
      out.write("                                        <option>S</option>\r\n");
      out.write("                                        <option>M</option>\r\n");
      out.write("                                        <option>L</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <input type=\"number\" id=\"num\" min=\"1\" max=\"100\" step=\"1\" value=\"1\">\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <button type=\"button\" id=\"by_now\">BUY IT NOW</button>\r\n");
      out.write("                            <button type=\"button\" id=\"shopping_bag\">SHOPPING BAG</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<!-- 내비게이션 시작 -->\r\n");
      out.write("<div id=\"section\">\r\n");
      out.write("    <hr>\r\n");
      out.write("    <div id=\"sec_details_nav\" class=\"sec_nav\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li class=\"sel_point\"><a href=\"#sec_details_nav\">THE DETAILS</a></li>\r\n");
      out.write("            <li><a href=\"#sec_review_nav\">REVIEW</a></li>\r\n");
      out.write("            <li><a href=\"#sec_QnA_nav\">Q&A</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"details_area\">\r\n");
      out.write("        <img src=\"images/detail/detail001.jpg\">\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--reivew-->\r\n");
      out.write("    <div id=\"sec_review_nav\" class=\"sec_nav\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"#sec_details_nav\">THE DETAILS</a></li>\r\n");
      out.write("            <li class=\"sel_point\"><a href=\"#sec_review_nav\">REVIEW</a></li>\r\n");
      out.write("            <li><a href=\"#sec_QnA_nav\">Q&A</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"review_area\">\r\n");
      out.write("        <form>\r\n");
      out.write("            <div class=\"rev_rate\">\r\n");
      out.write("                <select>\r\n");
      out.write("                    <option value=\"5\">★★★★★</option>\r\n");
      out.write("                    <option value=\"4\">★★★★☆</option>\r\n");
      out.write("                    <option value=\"3\">★★★☆☆</option>\r\n");
      out.write("                    <option value=\"2\">★★☆☆☆</option>\r\n");
      out.write("                    <option value=\"1\">★☆☆☆☆</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"rev_textArea\">\r\n");
      out.write("                <textarea rows=\"10\" placeholder=\"리뷰 등록 시 적립금을 드립니다!\"></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"rev_btns\">\r\n");
      out.write("                <p class=\"fileWrap\">\r\n");
      out.write("                    <input type=\"file\" id=\"rev_file\" name=\"rev_file\">\r\n");
      out.write("                    <span><i class=\"fas fa-camera\"></i></span>\r\n");
      out.write("                </p>\r\n");
      out.write("            <button class=\"rev_submit\" type=\"submit\">리뷰 등록</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--Q&A-->\r\n");
      out.write("    <div id=\"sec_QnA_nav\" class=\"sec_nav\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"#sec_details_nav\">THE DETAILS</a></li>\r\n");
      out.write("            <li><a href=\"#sec_review_nav\">REVIEW</a></li>\r\n");
      out.write("            <li class=\"sel_point\"><a href=\"#sec_QnA_nav\">Q&A</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <br>\r\n");
      out.write("    <div id=\"QnA_area\">\r\n");
      out.write("        <h3>상품 Q&A</h3>\r\n");
      out.write("        <button>상품문의 글쓰기</button>\r\n");
      out.write("        \r\n");
      out.write("        <br clear=\"both\"><br>\r\n");
      out.write("        <table>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>asd</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("\t<body>\n");
      out.write("\t\t<footer id=\"footer\">\n");
      out.write("\t        <div class=\"footer-wrap\">\n");
      out.write("\t            <div class=\"ft-top\">\n");
      out.write("\t                <ul>\n");
      out.write("\t                    <li><a href=\"#none\">고객센터</a></li>\n");
      out.write("\t                    <li><a href=\"#none\">서비스이용약관</a></li>\n");
      out.write("\t                    <li><a href=\"#none\"><b>개인정보취급방침</b></a></li>\n");
      out.write("\t                    <li><a href=\"#none\">이용안내</a></li>\n");
      out.write("\t                    <li><a href=\"#none\">광고/제휴문의</a></li>\n");
      out.write("\t                    <li><a href=\"#none\">사업자정보확인</a></li>\n");
      out.write("\t                </ul>\n");
      out.write("\t            </div>\n");
      out.write("\t            <div class=\"ft-bottom\">\n");
      out.write("\t                <p class=\"ft-logo\">FUN-THING</p>\n");
      out.write("\t                <div class=\"ft-cont\">\n");
      out.write("\t                    <span>(주)볼빨간조</span><span>대표 : 최상원</span><span>서울 강남구 테헤란로14길 6 남도빌딩 2층 B Class</span><span>통신판매업 신고번호 : 신고 준비중</span><br/>\n");
      out.write("\t                    <span>사업자번호 : 123-77-4567</span><span>개인정보관리책임자 : 조한솔</span><span>고객센터 대표전화 : 1234-5678</span><span>이메일 : rngus3698@naver.com</span>\n");
      out.write("\t                    <p class=\"copyright\">COPYRIGHTS 2020 FUNTHING. ALL RIGHTS RESERVED</p>\n");
      out.write("\t                </div>\n");
      out.write("\t\n");
      out.write("\t            </div>\n");
      out.write("\t        </div>\n");
      out.write("\t    </footer>\n");
      out.write("\t</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
