/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-05-25 06:25:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import product.model.vo.ProductDetail;
import productQnA.model.vo.AdminProductQnA;
import java.text.DecimalFormat;
import review.model.vo.*;
import member.model.vo.Member;

public final class productDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/product/../common/header.jsp", Long.valueOf(1590387855218L));
    _jspx_dependants.put("/views/product/../common/footer.jsp", Long.valueOf(1590387856008L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("review.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("product.model.vo.ProductDetail");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("productQnA.model.vo.AdminProductQnA");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- 제품 상세 페이지 _혜린,서윤  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	/* ProductDetail pd = (ProductDetail)request.getAttribute("pd"); */
	DecimalFormat formatter = new DecimalFormat("###,###");
	ArrayList<ProductDetail> list = (ArrayList<ProductDetail>)request.getAttribute("list");
	ArrayList<ProductDetail> sizeList = (ArrayList<ProductDetail>)request.getAttribute("sizeList");
	ArrayList<ProductDetail> colorList = (ArrayList<ProductDetail>)request.getAttribute("colorList");
	ArrayList<AdminProductQnA> qnaList = (ArrayList<AdminProductQnA>)request.getAttribute("qnaList");
	ProductDetail pd = list.get(0);
	int ratePrice = pd.getRetailPrice() * pd.getDcRate() / 100;
	
	// review
	ArrayList<Review> rvList = (ArrayList<Review>)request.getAttribute("rvList");
	String rvMsg = (String)request.getAttribute("rvMsg");
	
	int funded = (int)(((double)pd.getfSelPrice() /  pd.getfGoal()) *100);

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title></title>\r\n");
      out.write("    <!-- <script src=\"../js/jQuery-3.4.1.min.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/39b470622c.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("        body {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            font-family:  'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ul {\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            padding:5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #brand{\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            color:#30586e;\r\n");
      out.write("            font-size: initial;\r\n");
      out.write("        }\r\n");
      out.write("        #name{\r\n");
      out.write("            padding-bottom: 5px;\r\n");
      out.write("             border-bottom: 1.5px solid #30586e;\r\n");
      out.write("             font-size: large;\r\n");
      out.write("        }\r\n");
      out.write("        #product_description{\r\n");
      out.write("            font-size:small;\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        #prod-detail {\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #prod-detail:after {\r\n");
      out.write("            content: \"\";\r\n");
      out.write("            clear: both;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #photo {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 30%;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #photo_area {\r\n");
      out.write("            float: left;\r\n");
      out.write("            width: 30%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #p_detalis {\r\n");
      out.write("            float: left;\r\n");
      out.write("            width: 50%;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            padding: 0 0 0 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #right_wrap {margin-top: 15px;}\r\n");
      out.write("\r\n");
      out.write("        #right_wrap:after {\r\n");
      out.write("            content: \"\";\r\n");
      out.write("            clear: both;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #right_wrap ul {}\r\n");
      out.write("\r\n");
      out.write("        #right_wrap ul li {padding:1px;}\r\n");
      out.write("\r\n");
      out.write("        #right_wrap ul li:after {\r\n");
      out.write("            content: \"\";\r\n");
      out.write("            clear: both;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #right_wrap ul li .price_left {\r\n");
      out.write("            float: left;\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #right_wrap ul li .price_right {\r\n");
      out.write("            float: right;\r\n");
      out.write("            font-weight: 400;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .price {\r\n");
      out.write("            float: left;\r\n");
      out.write("            width: 40%;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            padding-right: 5%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .buy_information {\r\n");
      out.write("            float: right;\r\n");
      out.write("            width: 50%;\r\n");
      out.write("        }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("        .price_dis{\r\n");
      out.write("            color:red;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sizeColor{\r\n");
      out.write("            width: 265px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #num{\r\n");
      out.write("            width: 260px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #by_now, #shopping_bag{\r\n");
      out.write("            background:#9fa5a8;\r\n");
      out.write("            color:white;\r\n");
      out.write("            border:0;\r\n");
      out.write("            width:130px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 내비게이션 시작 */\r\n");
      out.write("        #section{margin: auto; width: 80%; height: 100%;}\r\n");
      out.write("        .sec_nav{margin: 0; width: 100%; height: 80px; background-color: rgb(223, 220, 220); text-align:center;}\r\n");
      out.write("\r\n");
      out.write("        .sec_nav ul {height: 100%; line-height: 80px; margin:0 auto; display:inline-block; }\r\n");
      out.write("        .sec_nav ul:after { clear:both; content:\"\"; display:block; }\r\n");
      out.write("        .sec_nav ul li {list-style: none; float: left; box-sizing:border-box; padding:0;}\r\n");
      out.write("        .sec_nav ul li a{text-decoration: none; margin-left: 100px; margin-right: 100px; color: black;}\r\n");
      out.write("\r\n");
      out.write("        .sec_nav .sel_point { background:#0f4a7e; }\r\n");
      out.write("        .sec_nav .sel_point a { display:inline-block; color:#fff; }\r\n");
      out.write("\r\n");
      out.write("        #details_area{margin: auto; width: 100%; text-align:center; }\r\n");
      out.write("\r\n");
      out.write("        #review_area{height: auto; width: 100%; /*border: 1px solid gray;*/ padding-bottom:40px; }\r\n");
      out.write("        #review_area .rev_rate  { width:100%; margin:20px 0 0; }\r\n");
      out.write("        #review_area .rev_rate select { width:100%; font-size:24px; height:50px; }\r\n");
      out.write("        #review_area .rev_textArea { box-sizing:border-box; margin: 20px 0 20px;  }\r\n");
      out.write("        #review_area .rev_textArea #rev_tit { width:100%; height:40px; margin-bottom:6px; box-sizing:border-box; font-size:18px; }\r\n");
      out.write("        #review_area .rev_textArea textarea { width:100%; resize: none; padding:10px; box-sizing:border-box; }\r\n");
      out.write("        #review_area .rev_textArea textarea::placeholder { color:#666; }\r\n");
      out.write("        #review_area .rev_btns { width:100%; }\r\n");
      out.write("        #review_area .rev_btns:after { display:block; content:\"\"; clear:both; }\r\n");
      out.write("        #review_area .rev_btns .rev_submit { float:right; width:160px; border-radius:0; height:60px; background:#30586e; color:#fff; font-size:16px; border:none; }\r\n");
      out.write("        #review_area .rev_btns .fileWrap { float:left; margin:0; width:60px; height:60px; overflow:hidden; position:relative; }\r\n");
      out.write("        #review_area .rev_btns .fileWrap input { font-size:40px; opacity:0; position:relative; z-index:2; }\r\n");
      out.write("        #review_area .rev_btns .fileWrap span { position:absolute; top:0; left:0; }\r\n");
      out.write("        #review_area .rev_btns .fileWrap span i { color:#30586e; font-size:60px; }\r\n");
      out.write("\r\n");
      out.write("        #QnA_area h3{float: left; font-size:x-large; color:#0f4a7e;}\r\n");
      out.write("        #QnA_area button{float: right; background-color: #30586e; border: 0px; height: 60px; color: white; font-size: 100%;}\r\n");
      out.write("        #QnA_area table{border-top: 2px solid rgb(223, 220, 220); border-bottom: 1px solid rgb(223, 220, 220); width: 100%;}\r\n");
      out.write("\r\n");
      out.write("\t\t#allBtn {padding-top : 10px;}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#qnaTb {border-collapse: collapse;}\r\n");
      out.write("\t\t#qnaTb tr {border-top: 1px solid grey;border-bottom: 1px solid grey; }\r\n");
      out.write("\t\t#qnaTb td {line-height: 50px; width: 40px; }\r\n");
      out.write("\t\t#qnaTb th {color:#0f4a7e;line-height: 50px; width: 40px;}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* review table */\r\n");
      out.write("\t\t.rev_content { width:100%; margin:40px 0; border-top:2px solid #ddd; border-bottom:2px solid #ddd; }\r\n");
      out.write("\t\t.rev_content .rev_table { width:100%; box-sizing:border-box; border-collapse: collapse; text-align:center; line-height:3; font-size:16px; }\r\n");
      out.write("\t\t.rev_content .rev_table tr { border-bottom:1px solid #ddd; }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.rev_content .rev_table tr th:nth-child(1) { width:50%; }\r\n");
      out.write("\t\t.rev_content .rev_table tr th:nth-child(2) { width:10%; }\r\n");
      out.write("\t\t.rev_content .rev_table tr th:nth-child(3) { width:10%; }\r\n");
      out.write("\t\t.rev_content .rev_table tr th:nth-child(4) { width:15%; }\r\n");
      out.write("\t\t.rev_content .rev_table tr th:nth-child(5) { width:15%; }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.rev_content .rev_table tr.rvCont td { text-align:left; box-sizing:border-box; padding:20px 10px; background:#f8f8f8; }\r\n");
      out.write("\t\t.rev_content .rev_table tr.rvCont td img { width:300px; border:1px solid #ddd; box-sizing:border-box; margin-right:40px; }\r\n");
      out.write("\t\t.rev_content .rev_table tr.rvCont td .divLeft { float:left; }\r\n");
      out.write("\t\t.rev_content .rev_table tr.rvCont td .divRight { float:left; width:70%; }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("        .rev_content .rev_table tr.rvCont { display:none; }\r\n");
      out.write("        .rev_content .rev_table tr.rvCont.show { display:table-row; }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* .border1{boarder-top:lightgrey; border-bottom:lightgrey;} */\r\n");
      out.write("\t\t.gauge{height:10px; width:19px; background:lightgrey; padding:0; maring:0; display:inline-block; border-top:1px solid lightgrey;border-bottom:1px solid lightgrey; }\r\n");
      out.write("\t\t.gaugewhite{height:10px; width:19px;background:white;padding:0; maring:0; color:white; display:inline-block; border-top:1px solid lightgrey;border-bottom:1px solid lightgrey;}\r\n");
      out.write("\t\t.leftradius{border-radius: 5px 0px 0px 5px; border-left:1px solid lightgrey;}\r\n");
      out.write("\t\t.rightradius{border-radius: 0px 5px 5px 0px; border-right:1px solid lightgrey;}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    ");

    	Member loginUser = (Member)session.getAttribute("loginUser");
    
      out.write(" \n");
      out.write("<!DOCTYPE html>\n");
      out.write("\t<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\n");
      out.write("\t\t<meta charset=\"UTF-8\">\n");
      out.write("\t\t<title>Insert title here</title>\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/main.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/reset.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\">\n");
      out.write("\t    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/slick/slick.css\"/>\n");
      out.write("\t    <!-- Add the new slick-theme.css if you want the default styling -->\n");
      out.write("\t    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/slick/slick-theme.css\"/>\n");
      out.write("\t\t\n");
      out.write("  \t\t  <script src=\"https://kit.fontawesome.com/39b470622c.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("\t\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/action.js\"></script>\n");
      out.write("\t\t<!--script src=\"<!--%=request.getContextPath()%>/js/swiper.min.js\"></script-->\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/slick/slick.min.js\"></script>\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t\t<header id=\"header\">\n");
      out.write("\t       <div class=\"menu-wrap\">\n");
      out.write("               <div class=\"log-menu\">\n");
      out.write("               \n");
      out.write("               ");
 if(loginUser != null){ 
      out.write("\n");
      out.write("                   <ul class=\"log-sec login\">\n");
      out.write("                   ");
if(loginUser.getmId().equals("master")){ 
      out.write("\n");
      out.write("                      <li class=\"master\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/mainView\">MASTER</a></li>\n");
      out.write("                      ");
} 
      out.write("\n");
      out.write("                       <li><a href=\"#none\">HELP</a></li>\n");
      out.write("                       <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/logout.me\">LOGOUT</a></li>\n");
      out.write("                       ");
if(loginUser.getmId().equals("master")){ 
      out.write("\n");
      out.write("                       \t\t<li><a style=\"display:none;\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPageMainServlet?userNoM=");
      out.print(loginUser.getmNo());
      out.write("\">MY PAGE</a></li>\n");
      out.write("                       ");
}else{ 
      out.write("\n");
      out.write("                        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/myPageMainServlet?userNoM=");
      out.print(loginUser.getmNo());
      out.write("\">MY PAGE</a></li>\n");
      out.write("                       ");
} 
      out.write("\n");
      out.write("                       <li><a href=\"#none\"><i class=\"fas fa-shopping-cart\"></i></a></li>\n");
      out.write("                   </ul>\n");
      out.write("                   ");
 }else{ 
      out.write("\n");
      out.write("                   <ul class=\"log-sec logout\">\n");
      out.write("                       <li><a href=\"#none\">HELP</a></li>\n");
      out.write("                       <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/member/memberJoin.jsp\">JOIN</a></li>\n");
      out.write("                       <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/member/memberLogin.jsp\">LOGIN</a></li>\n");
      out.write("                       <li><a href=\"#none\"><i class=\"fas fa-shopping-cart\"></i></a></li>\n");
      out.write("                   </ul>\n");
      out.write("                   ");
 } 
      out.write("\n");
      out.write("                   \n");
      out.write("               </div>\n");
      out.write("           </div>\n");
      out.write("\t        <div id=\"nav-wrap\">\n");
      out.write("\t            <div class=\"logo-wrap\">\n");
      out.write("\t                <h1 class=\"logo\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/index.jsp\">FUN-THING</a></h1>\n");
      out.write("\t                \n");
      out.write("\t                <div class=\"search-box\"><span><i class=\"fas fa-search\"></i></span></div>\n");
      out.write("\t                \n");
      out.write("\t            </div>\n");
      out.write("\t            <nav id=\"nav\">\n");
      out.write("\t                <ul>\n");
      out.write("\t                    <li>\n");
      out.write("\t                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/WomenServlet\">WOMAN</a>\n");
      out.write("\t                        <ul class=\"sub-menu\">\n");
      out.write("\t                            <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/WomenOuterServlet\">OUTER</a></li>\n");
      out.write("\t                            <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/WomenTopServlet\">TOP</a></li>\n");
      out.write("\t                            <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/WomenBottomServlet\">BOTTOM</a></li>\n");
      out.write("\t                            <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/WomenJeanServlet\">JEAN</a></li>\n");
      out.write("\t                            <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/WomenOnepieceServlet\">ONEPIECE</a></li>\n");
      out.write("\t                        </ul>\n");
      out.write("\t                    </li>\n");
      out.write("\t                    <li>\n");
      out.write("\t                    \n");
      out.write("\t                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/ManServlet\">MAN</a>\n");
      out.write("\t                        <ul class=\"sub-menu\">\n");
      out.write("\t                            <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/ManOuterServlet\">OUTER</a></li>\n");
      out.write("\t                            <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/ManTopServlet\">TOP</a></li>\n");
      out.write("\t                            <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/ManBottomServlet\">BOTTOM</a></li>\n");
      out.write("\t                            <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/ManJeanServlet\">JEAN</a></li>\n");
      out.write("\t                        </ul>\n");
      out.write("\t                    </li>\n");
      out.write("\t                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/CalendarSelect\">CALENDAR</a></li>\n");
      out.write("\t                </ul>\n");
      out.write("\t            </nav>\n");
      out.write("\t        </div>\n");
      out.write("\t        <!-- nav end -->\n");
      out.write("\t    </header>\n");
      out.write("\t    \n");
      out.write("\t    <div class=\"searchWrap\">\n");
      out.write("\t        <form id=\"search\" action=\"");
      out.print(request.getContextPath() );
      out.write("/MainSearch\" method=\"GET\">\n");
      out.write("\t        \n");
      out.write("\t            <input type=\"text\" id=\"search\" name=\"search\" /><button type=\"submit\" id=\"submitBtn\" style=\"background-color:transparent; border:0px;\"><i class=\"fas fa-search\"></i></button>\n");
      out.write("\t        </form>\n");
      out.write("\t        <div class=\"close\"><i class=\"fas fa-times\"></i></div>\n");
      out.write("\t    </div>\n");
      out.write("\t</body>\n");
      out.write("\t \n");
      out.write("\t<script>\n");
      out.write("\t\t//헤더 상단 고정\n");
      out.write("\t\tvar headerTop = $(\"#header\").offset();\n");
      out.write("\t\tconsole.log(headerTop);\n");
      out.write("\t\t$(window).scroll(function(){\n");
      out.write("\t\t  if($(document).scrollTop() > headerTop.top){\n");
      out.write("\t\t    $(\"#header\").addClass(\"fixed\");\n");
      out.write("\t\t  }else{\n");
      out.write("\t\t    $(\"#header\").removeClass(\"fixed\");\n");
      out.write("\t\t  }\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t// 검색창 클릭 시\n");
      out.write("\t\t$(\".search-box\").click(function(){\n");
      out.write("\t\t    $(\".searchWrap\").show();\n");
      out.write("\t\t    $('html').css({'overflow': 'hidden', 'height': '100%'});\n");
      out.write("\t\t    $('#element').on('scroll touchmove mousewheel', function(event) {\n");
      out.write("\t\t      event.preventDefault();\n");
      out.write("\t\t      event.stopPropagation();\n");
      out.write("\t\t      return false;\n");
      out.write("\t\t    });\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t// 검색창 열렸을 때 닫기\n");
      out.write("\t\t$(\".searchWrap .close\").click(function(){\n");
      out.write("\t\t  $(\".searchWrap\").hide();\n");
      out.write("\t\t  $('html').css({'overflow': 'scroll', 'height': '100%'});\n");
      out.write("\t\t  $('#element').off('scroll touchmove mousewheel');\n");
      out.write("\t\t\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t//nav menu\n");
      out.write("\t\t$(\"#nav > ul > li .sub-menu\").hide();\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"#nav > ul > li\").hover(function(){\n");
      out.write("\t\t  $(this).children(\".sub-menu\").stop().slideDown();\n");
      out.write("\t\t}, function(){\n");
      out.write("\t\t  $(this).children(\".sub-menu\").stop().slideUp();\n");
      out.write("\t\t\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
if(!list.isEmpty() && !sizeList.isEmpty()){ 
      out.write(" \r\n");
      out.write("    <div id=\"prod-detail\">\r\n");
      out.write("        <!-- 상품 정보 -->\r\n");
      out.write("        <div id=\"detail_top\">\r\n");
      out.write("            <div id=\"photo_area\">\r\n");
      out.write("                <img id=\"photo\" name=\"photo\" src=\"");
      out.print(request.getContextPath()+"/images/thumbnail/" + pd.getThumbnail() + ".jpg" );
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"p_detalis\" name=\"p_detalis\">\r\n");
      out.write("                <ul id=\"product_ul\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div id=\"brand\" name=\"brand\">");
      out.print( pd.getbName() );
      out.write("</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div id=\"name\" name=\"name\">");
      out.print( pd.getpName() );
      out.write("</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div id=\"product_description\">");
      out.print( pd.getpDetail() );
      out.write("</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <input type=\"hidden\" name=\"hiddenPno\" value=\"");
      out.print( pd.getpNo() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                <!-- 상품 판매가 -->\r\n");
      out.write("                <div id=\"right_wrap\">\r\n");
      out.write("                    <ul class=\"price\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"price_left\">정상가</span><span class=\"price_right\"><s>");
      out.print( formatter.format(pd.getRetailPrice()) );
      out.write("</s></span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("                            <span class=\"price_left\">할인가</span><span class=\"price_right\">\r\n");
      out.write("                            <span class=\"price_dis\">");
      out.print( pd.getDcRate());
      out.write("%▼</span><span>");
      out.print(formatter.format(ratePrice) );
      out.write("</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"price_left\">적립금</span><span class=\"price_right\">");
      out.print(formatter.format(pd.getpPoint()) );
      out.write("</span> \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"price_left\">회원가</span> <span class=\"price_right\">");
      out.print(formatter.format(pd.getpPrice()) );
      out.write("</span>\r\n");
      out.write("                                    \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li style=\"padding-top:25px;\">\r\n");
      out.write("                        \t<div align=\"right\" style=\"color:grey;\">");
      out.print( funded );
      out.write(" % Funded</div>\r\n");
      out.write(" \t\t\t\t\t\t\t<!-- <div class=\"gauge leftradius\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge rightradius\"></div> -->\r\n");
      out.write(" \t\t\t\t\t\t\t");
if(funded == 0 ){ 
      out.write("     \r\n");
      out.write(" \t\t\t\t\t\t\t<div class=\"gaugewhite leftradius\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite rightradius\"></div>                  \r\n");
      out.write("                        \t");
}else if(1<= funded && funded <=10 ){ 
      out.write("\r\n");
      out.write("                            <div class=\"gauge leftradius\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite rightradius\"></div>        \r\n");
      out.write(" \t\t\t\t\t\t\t");
}else if(11<= funded && funded <=20){
      out.write("\r\n");
      out.write(" \t\t\t\t\t\t\t<div class=\"gauge leftradius\"></div><div class=\"gauge\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite rightradius\"></div>\r\n");
      out.write(" \t\t\t\t\t\t\t");
}else if(21<= funded && funded <=30){
      out.write("\r\n");
      out.write(" \t\t\t\t\t\t\t<div class=\"gauge leftradius\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite rightradius\"></div>\r\n");
      out.write(" \t\t\t\t\t\t\t");
}else if(31<= funded && funded <=40){
      out.write("\r\n");
      out.write(" \t\t\t\t\t\t\t<div class=\"gauge leftradius\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite rightradius\"></div>\r\n");
      out.write(" \t\t\t\t\t\t\t");
}else if(41<= funded && funded <=50){
      out.write("\r\n");
      out.write(" \t\t\t\t\t\t\t<div class=\"gauge leftradius\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite rightradius\"></div>\r\n");
      out.write(" \t\t\t\t\t\t\t");
}else if(51<= funded && funded <=60){
      out.write("\r\n");
      out.write(" \t\t\t\t\t\t\t<div class=\"gauge leftradius\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite rightradius\"></div>\r\n");
      out.write(" \t\t\t\t\t\t\t");
}else if(61<= funded && funded <=70){
      out.write("\r\n");
      out.write(" \t\t\t\t\t\t\t<div class=\"gauge leftradius\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite rightradius\"></div>\r\n");
      out.write(" \t\t\t\t\t\t\t");
}else if(71<= funded && funded <=80){
      out.write("\r\n");
      out.write(" \t\t\t\t\t\t\t<div class=\"gauge leftradius\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gaugewhite\"></div><div class=\"gaugewhite rightradius\"></div>\r\n");
      out.write(" \t\t\t\t\t\t\t");
}else if(81<= funded && funded <=90){
      out.write("\r\n");
      out.write(" \t\t\t\t\t\t\t<div class=\"gauge leftradius\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gaugewhite rightradius\"></div>\r\n");
      out.write(" \t\t\t\t\t\t\t");
}else if(91<= funded && funded <=100){
      out.write("\t                      \r\n");
      out.write(" \t\t\t\t\t\t\t<div class=\"gauge leftradius\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge\"></div><div class=\"gauge rightradius\"></div>\r\n");
      out.write(" \t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("                       \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li style=\"padding-top:5px;\">\r\n");
      out.write("                            <div align=\"right\" style=\"color:grey;\">Funding Ends</div><h4 align=\"right\" id=\"sample04\"  style=\"color:#30586e;\"></h4>\t\r\n");
      out.write("                                    \r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("\t\t\t\t\t<!-- 타이머 script -->\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t            const countDownTimer = function (id, date) {\r\n");
      out.write("\t\t                var _vDate = new Date(date); // 전달 받은 일자\r\n");
      out.write("\t\t                var _second = 1000;\r\n");
      out.write("\t\t                var _minute = _second * 60;\r\n");
      out.write("\t\t                var _hour = _minute * 60;\r\n");
      out.write("\t\t                var _day = _hour * 24;\r\n");
      out.write("\t\t                var timer;\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t                function showRemaining() {\r\n");
      out.write("\t\t                    var now = new Date();\r\n");
      out.write("\t\t                    var distDt = _vDate - now;\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t                    if (distDt < 0) {\r\n");
      out.write("\t\t                        clearInterval(timer);\r\n");
      out.write("\t\t                        document.getElementById(id).textContent = '해당 이벤트가 종료 되었습니다!';\r\n");
      out.write("\t\t                        return;\r\n");
      out.write("\t\t                    }\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t                    var days = Math.floor(distDt / _day);\r\n");
      out.write("\t\t                    var hours = Math.floor((distDt % _day) / _hour);\r\n");
      out.write("\t\t                    var minutes = Math.floor((distDt % _hour) / _minute);\r\n");
      out.write("\t\t                    var seconds = Math.floor((distDt % _minute) / _second);\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t                    //document.getElementById(id).textContent = date.toLocaleString() + \"까지 : \";\r\n");
      out.write("\t\t                    document.getElementById(id).textContent = days + ' d ';\r\n");
      out.write("\t\t                    document.getElementById(id).textContent += hours + ' h ';\r\n");
      out.write("\t\t                    document.getElementById(id).textContent += minutes + ' m ';\r\n");
      out.write("\t\t                    document.getElementById(id).textContent += seconds + ' s ';\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t                timer = setInterval(showRemaining, 1000);\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t            var dateObj = new Date();\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            countDownTimer('sample04', '  ");
      out.print(pd.getfEndDate() );
      out.write("'); \r\n");
      out.write("\t\t            /* countDownTimer('sample04', '2020/05/28'); // 2024년 4월 1일까지 */\r\n");
      out.write("     \t\t\t   </script>\r\n");
      out.write("     \t\t\t \r\n");
      out.write("                    <!-- 상품 선택 및 구매/장바구니 -->\r\n");
      out.write("                    <div class=\"buy_information\">\r\n");
      out.write("                    \r\n");
      out.write("                        <form method=\"get\" action=\"");
      out.print(request.getContextPath());
      out.write("/PaymentInfo\" id=\"colorSizeform\">\r\n");
      out.write("                            <ul id=\"buyList\">\r\n");
      out.write("                            ");
if(loginUser != null){ 
      out.write("\r\n");
      out.write("                             <input type=\"hidden\" name=\"pNo\" value=\"");
      out.print(list.get(1).getpNo());
      out.write("\">\r\n");
      out.write("                             <input type=\"hidden\" name=\"p_no\" value=\"");
      out.print(list.get(1).getpNo());
      out.write("\">\r\n");
      out.write("                          \t  <input type=\"hidden\" name=\"userNo\" value=\"");
      out.print(loginUser.getmNo() );
      out.write("\"> \r\n");
      out.write("\n");
      out.write("                          \t  <input type=\"hidden\" name=\"mEmail\" value=\"");
      out.print(loginUser.getmEmail() );
      out.write("\"> \r\n");
      out.write("                          \t  <input type=\"hidden\" name=\"pName\" value=\"");
      out.print(pd.getpName() );
      out.write("\">\r\n");
      out.write("                          \t  <input type=\"hidden\" name=\"bNo\" value=\"");
      out.print(pd.getbNo() );
      out.write("\"> \r\n");
      out.write("                          \t  <input type=\"hidden\" name=\"bName\" value=\"");
      out.print(pd.getbName() );
      out.write("\"> \r\n");
      out.write("\n");
      out.write("                          \t  ");
      out.write("\r\n");
      out.write("\n");
      out.write("                            ");
}else{ 
      out.write("\r\n");
      out.write("                           \t <input type=\"hidden\" name=\"p_no\" value=\"");
      out.print(list.get(1).getpNo());
      out.write("\">\r\n");
      out.write("                           \t ");
      out.write("\r\n");
      out.write("                           \t ");
      out.write("\r\n");
      out.write("                            ");
 } 
      out.write("\t \r\n");
      out.write("                            \t <li>\r\n");
      out.write("                                   <select class=\"sizeColor\" id=\"color\" name=\"color\">\r\n");
      out.write("                                     <option value=\"noColor\">color 선택</option>\r\n");
      out.write("                                    ");
for(ProductDetail pDetail : colorList){ 
      out.write("\r\n");
      out.write("                                   \r\n");
      out.write("\t                                 \t");
if(pDetail.getpColor().equals("BK")){ 
      out.write("\r\n");
      out.write("\t                                    <option value=\"BK\">BLACK</option>\r\n");
      out.write("\t                                   ");
} 
      out.write("\r\n");
      out.write("\t                                   ");
if(pDetail.getpColor().equals("BL")){ 
      out.write("\r\n");
      out.write("\t                                   <option value=\"BL\">BLUE</option>\r\n");
      out.write("\t                                    ");
} 
      out.write("\r\n");
      out.write("\t                                   ");
if(pDetail.getpColor().equals("WH")){ 
      out.write("\r\n");
      out.write("\t                                   <option value=\"WH\">WHITE</option>\r\n");
      out.write("\t                                    ");
} 
      out.write("\r\n");
      out.write("\t                                   ");
if(pDetail.getpColor().equals("RD")){ 
      out.write("\r\n");
      out.write("\t                                   <option value=\"RD\">RED</option>\r\n");
      out.write("\t                                    ");
} 
      out.write("\r\n");
      out.write("\t                                   ");
if(pDetail.getpColor().equals("KH")){ 
      out.write("\r\n");
      out.write("\t                                   <option value=\"KH\">KHAKI</option>\r\n");
      out.write("\t                                    ");
} 
      out.write("\r\n");
      out.write("\t                                   ");
if(pDetail.getpColor().equals("YL")){ 
      out.write("\r\n");
      out.write("\t                                   <option value=\"YL\">YELLOW</option>\r\n");
      out.write("\t                                    ");
} 
      out.write("\r\n");
      out.write("\t                                   ");
if(pDetail.getpColor().equals("GN")){ 
      out.write("\r\n");
      out.write("\t                                   <option value=\"GN\">GREEN</option>\r\n");
      out.write("                                   \t\t");
} 
      out.write(" \r\n");
      out.write("                                    ");
} 
      out.write("\r\n");
      out.write("                                    </select> \r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <select class=\"sizeColor\" id=\"size\" name=\"size\">\r\n");
      out.write("                                        <option value=\"noSize\">size 선택</option>\r\n");
      out.write("                                       ");
for(ProductDetail pro : sizeList){ 
      out.write(" \r\n");
      out.write("                                    <option value=\"");
      out.print( pro.getpSize() );
      out.write('"');
      out.write('>');
      out.print( pro.getpSize() );
      out.write("</option>\r\n");
      out.write("                                    ");
} 
      out.write("\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <input type=\"number\" name=\"number\" id=\"num\" min=\"1\" max=\"100\" step=\"1\" value=\"1\">\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                           \r\n");
      out.write("                            <div id=\"allBtn\" >\r\n");
      out.write("                            <button type=\"button\" id=\"by_now\" onclick=\"byNow();\">BUY IT NOW</button>\r\n");
      out.write("                            <button type=\"button\" onclick=\"shoppingBag();\" id=\"shopping_bag\" >SHOPPING BAG</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("       \tfunction byNow(){\r\n");
      out.write("       \t\t\tif($(\"#color option:selected\").val() != \"noColor\" &&  $(\"#size option:selected\").val() != \"noSize\"  ){\r\n");
      out.write("    \t\t\t\t$(\"#colorSizeform\").submit();\r\n");
      out.write("    \t\t\t}else{\r\n");
      out.write("           \t\t\talert(\"색상, 사이즈, 수량을 선택해주세요\");\r\n");
      out.write("           \t\t}\r\n");
      out.write("       \t\t}\r\n");
      out.write("       \t\r\n");
      out.write("       \tfunction shoppingBag(){\r\n");
      out.write("       \t\tif($(\"#color option:selected\").val() != \"noColor\" &&  $(\"#size option:selected\").val() != \"noSize\"  ){\r\n");
      out.write("\t\t\t\t$(\"#colorSizeform\").attr(\"action\", \"");
      out.print(request.getContextPath() );
      out.write("/SBInsertServlet\");\r\n");
      out.write("       \t\t\t$(\"#colorSizeform\").submit();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("       \t\t\talert(\"색상, 사이즈, 수량을 선택해주세요\");\r\n");
      out.write("       \t\t}\r\n");
      out.write("       \t}\r\n");
      out.write("    \t$(function(){\r\n");
      out.write("    \r\n");
      out.write("                 ");
if(loginUser != null){
      out.write("\r\n");
      out.write("    \t\t\t$(\"#by_now\").attr(\"disabled\",false);\r\n");
      out.write("    \t\t\t$(\"#shopping_bag\").attr(\"disabled\",false);\r\n");
      out.write("\r\n");
      out.write("    \t\t\t");
}else{
      out.write("\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t$(\"#by_now\").attr(\"disabled\",true);\r\n");
      out.write("    \t\t\t$(\"#shopping_bag\").attr(\"disabled\",true);\r\n");
      out.write("    \t\t\t");
}
      out.write("\r\n");
      out.write("    \t}) \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("<!-- 내비게이션 시작 -->\r\n");
      out.write("<div id=\"section\">\r\n");
      out.write("    <hr>\r\n");
      out.write("    <div id=\"sec_details_nav\" class=\"sec_nav\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li class=\"sel_point\"><a href=\"#sec_details_nav\">THE DETAILS</a></li>\r\n");
      out.write("            <li><a href=\"#sec_review_nav\">REVIEW</a></li>\r\n");
      out.write("            <li><a href=\"#sec_QnA_nav\">Q&A</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"details_area\">\r\n");
      out.write("        <!-- <img src=\"images/detail/detail001.jpg\"> -->\r\n");
      out.write("        <img id=\"photo\" name=\"photo\" src=\"");
      out.print(request.getContextPath()+"/images/thumbnail/" + pd.getImgRoter() + ".jpg" );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--reivew-->\r\n");
      out.write("    <div id=\"sec_review_nav\" class=\"sec_nav\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"#sec_details_nav\">THE DETAILS</a></li>\r\n");
      out.write("            <li class=\"sel_point\"><a href=\"#sec_review_nav\">REVIEW</a></li>\r\n");
      out.write("            <li><a href=\"#sec_QnA_nav\">Q&A</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"review_area\">\r\n");
      out.write("        <form action=\"");
      out.print(request.getContextPath());
      out.write("/ReviewInsert\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("        \t<input type=\"hidden\" name=\"rev_pNo\" value=\"");
      out.print( pd.getpNo() );
      out.write("\" />\r\n");
      out.write("        \t<input type=\"hidden\" name=\"rev_pName\" value=\"");
      out.print( pd.getpName() );
      out.write("\" />\r\n");
      out.write("            <div class=\"rev_rate\">\r\n");
      out.write("                <select name=\"rev_rateS\" id=\"rev_rateS\">\r\n");
      out.write("                    <option value=\"5\">★★★★★</option>\r\n");
      out.write("                    <option value=\"4\">★★★★☆</option>\r\n");
      out.write("                    <option value=\"3\">★★★☆☆</option>\r\n");
      out.write("                    <option value=\"2\">★★☆☆☆</option>\r\n");
      out.write("                    <option value=\"1\">★☆☆☆☆</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"rev_textArea\">\r\n");
      out.write("            \t<input type=\"text\" id=\"rev_tit\" name=\"rev_tit\" placeholder=\"리뷰 제목을 입력하세요.\" required/>\r\n");
      out.write("                <textarea name=\"rev_textArea\" rows=\"10\" placeholder=\"리뷰 등록 시 적립금을 드립니다!\" required></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"rev_btns\">\r\n");
      out.write("                <p class=\"fileWrap\">\r\n");
      out.write("                    <input type=\"file\" id=\"rev_file\" name=\"rev_file\">\r\n");
      out.write("                    <span><i class=\"fas fa-camera\"></i></span>\r\n");
      out.write("                </p>\r\n");
      out.write("            <button class=\"rev_submit\" type=\"submit\">리뷰 등록</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <div class=\"rev_content\">\r\n");
      out.write("        \t<table class=\"rev_table\">\r\n");
      out.write("        \t\t<tr>\r\n");
      out.write("        \t\t\t<!-- th>No</th-->\r\n");
      out.write("        \t\t\t<th>Title</th>\r\n");
      out.write("        \t\t\t<th>Rate</th>\r\n");
      out.write("        \t\t\t<th>View</th>\r\n");
      out.write("        \t\t\t<th>Writer</th>\r\n");
      out.write("        \t\t\t<th>Date</th>\r\n");
      out.write("        \t\t</tr>\r\n");
      out.write("        \t</table>\r\n");
      out.write("        <!-- 리뷰 불러올 부분 -->\r\n");
      out.write("        <script>\r\n");
      out.write("        if(\"");
      out.print(rvMsg);
      out.write("\" != \"null\"){\r\n");
      out.write("        \talert(\"");
      out.print(rvMsg);
      out.write("\");\r\n");
      out.write("        }\r\n");
      out.write("        $(window).load(function(){\r\n");
      out.write("        \t$.ajax({\r\n");
      out.write("        \t\turl : \"");
      out.print(request.getContextPath());
      out.write("/ReviewList\",\r\n");
      out.write("        \t\ttype : \"post\",\r\n");
      out.write("        \t\tdata : {\"rev_pNo\" : \"");
      out.print( pd.getpNo() );
      out.write("\"},\r\n");
      out.write("        \t\tsuccess : function(data){\r\n");
      out.write("        \t\t\t//alert(\"성공\");\r\n");
      out.write("        \t\t\t\r\n");
      out.write("        \t\t\t$.each(data, function(index, value){\r\n");
      out.write("        \t\t\t\t// 제목 부분\r\n");
      out.write("        \t\t\t\tvar $trLine = $(\"<tr>\").attr(\"class\", \"rvLine\");\r\n");
      out.write("        \t\t\t\t// var $tdNo = $(\"<td>\").text(value.rvNo);\r\n");
      out.write("        \t\t\t\tvar $tdTitle = $(\"<td>\").text(value.rvTitle);\r\n");
      out.write("        \t\t\t\tvar $tdRate = $(\"<td>\").text(value.rvRateStar);\r\n");
      out.write("        \t\t\t\tvar $tdView = $(\"<td>\").text(value.rvView);\r\n");
      out.write("        \t\t\t\tvar $tdWriter = $(\"<td>\").text(value.rvName);\r\n");
      out.write("        \t\t\t\tvar $tdDate = $(\"<td>\").text(value.rvDate);\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\t// 컨텐츠 부분\r\n");
      out.write("        \t\t\t\tvar $trCont = $(\"<tr>\").attr(\"class\", \"rvCont\");\r\n");
      out.write("        \t\t\t\tvar $tdCont = $(\"<td>\").attr(\"colspan\", \"5\");\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\tvar $divLeft = $(\"<div>\").attr(\"class\", \"divLeft\");\r\n");
      out.write("        \t\t\t\tvar $divRight = $(\"<div>\").attr(\"class\", \"divRight\");\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\tif(value.rvImg != null){\r\n");
      out.write("        \t\t\t\t\tvar $pImgArea = $(\"<p>\");\r\n");
      out.write("        \t\t\t\t\tvar $pImg = $(\"<img>\").attr(\"src\", \"");
      out.print(request.getContextPath());
      out.write("/images/review/\" + value.rvImg + \".jpg\");\r\n");
      out.write("        \t\t\t\t\t\r\n");
      out.write("        \t\t\t\t\t$pImgArea.append($pImg);\r\n");
      out.write("        \t\t\t\t\t$divLeft.append($pImgArea);\r\n");
      out.write("        \t\t\t\t\t$tdCont.append($divLeft);\r\n");
      out.write("        \t\t\t\t}\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\tvar $pPrdNo = $(\"<p>\").text(\"상품명 : \" + value.rvpNo);\r\n");
      out.write("        \t\t\t\tvar $pContt = $(\"<p>\").text(value.rvContents);\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\t// $tr.append($tdNo);\r\n");
      out.write("        \t\t\t\t$trLine.append($tdTitle);\r\n");
      out.write("        \t\t\t\t$trLine.append($tdRate);\r\n");
      out.write("        \t\t\t\t$trLine.append($tdView);\r\n");
      out.write("        \t\t\t\t$trLine.append($tdWriter);\r\n");
      out.write("        \t\t\t\t$trLine.append($tdDate);\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\t$divRight.append($pPrdNo);\r\n");
      out.write("        \t\t\t\t$divRight.append($pContt);\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\t$tdCont.append($divRight);\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\t$trCont.append($tdCont);\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\t$(\".rev_table\").append($trLine);\r\n");
      out.write("        \t\t\t\t$(\".rev_table\").append($trCont);\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t});\r\n");
      out.write("\r\n");
      out.write("                    $(\".rvLine\").click(function(){\r\n");
      out.write("                        $(this).next().toggleClass(\"show\");\r\n");
      out.write("                    });\r\n");
      out.write("        \t\t\t\r\n");
      out.write("        \t\t},\r\n");
      out.write("        \t\terror : function(data){\r\n");
      out.write("        \t\t\talert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("        \t\t}\r\n");
      out.write("        \t});\r\n");
      out.write("        \t// ajax end\r\n");
      out.write("        \t\r\n");
      out.write("        });\r\n");
      out.write("        </script>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--Q&A-->\r\n");
      out.write("    <div id=\"sec_QnA_nav\" class=\"sec_nav\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"#sec_details_nav\">THE DETAILS</a></li>\r\n");
      out.write("            <li><a href=\"#sec_review_nav\">REVIEW</a></li>\r\n");
      out.write("            <li class=\"sel_point\"><a href=\"#sec_QnA_nav\">Q&A</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <br>\r\n");
      out.write("    <div id=\"QnA_area\">\r\n");
      out.write("        <h3>상품 Q&A</h3>\r\n");
      out.write("        ");
if(loginUser != null){ 
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <button onclick=\"productInsertQna();\">상품문의 글쓰기</button>\r\n");
      out.write("        ");
}else { 
      out.write("\r\n");
      out.write("        <button onclick=\"productQna();\">상품문의 글쓰기</button>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("        <br clear=\"both\"><br>\r\n");
      out.write("        <table id=\"qnaTb\">\r\n");
      out.write("            <tbody>\r\n");
      out.write("            \t");
 if(!qnaList.isEmpty()){ 
      out.write("\r\n");
      out.write("            \t <tr>\r\n");
      out.write("                     <th align=\"center\">아이디</th><th align=\"center\">제목</th><th align=\"center\">작성날짜</th>\r\n");
      out.write("                    \r\n");
      out.write("                </tr>\r\n");
      out.write("            \t");
for(AdminProductQnA ap : qnaList){ 
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td align=\"center\">");
      out.print( ap.getmId() );
      out.write("</td><td align=\"center\">");
      out.print( ap.getQnaTitle() );
      out.write("</td><td align=\"center\">");
      out.print( ap.getQnaDate() );
      out.write("</td>\r\n");
      out.write("                    \r\n");
      out.write("                </tr>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("                    <th align=\"center\">아이디</th><th align=\"center\">제목</th><th align=\"center\">작성날짜</th>\r\n");
      out.write("                    \r\n");
      out.write("                </tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("                    <td colspan=\"3\" align=\"center\">상품문의글이 없습니다.</td>\r\n");
      out.write("                    \r\n");
      out.write("                </tr>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
} 
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction productQna(){\r\n");
      out.write("\t\talert(\"로그인을 후 입력이 가능합니다.\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction productInsertQna(){\r\n");
      out.write("\t\tif($(\"#color\").val() == \"noColor\" && $(\"#size\").val() == \"noSize\"){\r\n");
      out.write("\t\t\talert(\"색상과 사이즈 선택 후 문의를 해주세요.\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t$(\"#colorSizeform\").attr(\"action\",\"");
      out.print(request.getContextPath());
      out.write("/views/productQnA/productQnAInsert.jsp\");\r\n");
      out.write("\t\t$(\"#colorSizeform\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\t");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("\t<body>\n");
      out.write("\t\t<footer id=\"footer\">\n");
      out.write("\t        <div class=\"footer-wrap\">\n");
      out.write("\t            <div class=\"ft-top\">\n");
      out.write("\t                <ul>\n");
      out.write("\t                    <li><a href=\"#none\">고객센터</a></li>\n");
      out.write("\t                    <li><a href=\"#none\">서비스이용약관</a></li>\n");
      out.write("\t                    <li><a href=\"#none\"><b>개인정보취급방침</b></a></li>\n");
      out.write("\t                    <li><a href=\"#none\">이용안내</a></li>\n");
      out.write("\t                    <li><a href=\"#none\">광고/제휴문의</a></li>\n");
      out.write("\t                    <li><a href=\"#none\">사업자정보확인</a></li>\n");
      out.write("\t                </ul>\n");
      out.write("\t            </div>\n");
      out.write("\t            <div class=\"ft-bottom\">\n");
      out.write("\t                <p class=\"ft-logo\">FUN-THING</p>\n");
      out.write("\t                <div class=\"ft-cont\">\n");
      out.write("\t                    <span>(주)볼빨간조</span><span>대표 : 최상원</span><span>서울 강남구 테헤란로14길 6 남도빌딩 2층 B Class</span><span>통신판매업 신고번호 : 신고 준비중</span><br/>\n");
      out.write("\t                    <span>사업자번호 : 123-77-4567</span><span>개인정보관리책임자 : 조한솔</span><span>고객센터 대표전화 : 1234-5678</span><span>이메일 : rngus3698@naver.com</span>\n");
      out.write("\t                    <p class=\"copyright\">COPYRIGHTS 2020 FUNTHING. ALL RIGHTS RESERVED</p>\n");
      out.write("\t                </div>\n");
      out.write("\t\n");
      out.write("\t            </div>\n");
      out.write("\t        </div>\n");
      out.write("\t        <!-- footer wrap end -->\n");
      out.write("\t        <div class=\"sc-btns\">\n");
      out.write("\t            <p class=\"up\"><i class=\"fas fa-arrow-up\"></i></p>\n");
      out.write("\t            <p class=\"down\"><i class=\"fas fa-arrow-down\"></i></p>\n");
      out.write("\t        </div>\n");
      out.write("\t    </footer>\n");
      out.write("\t</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
