/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-05-16 07:04:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modifyMember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/admin/../common/adminHeader.jsp", Long.valueOf(1589612595109L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>Insert title here</title>\r\n");
      out.write("        <style>\r\n");
      out.write("            .btn{\r\n");
      out.write("                padding: 15px;\r\n");
      out.write("                margin-left: 25px;\r\n");
      out.write("                width: 150px;\r\n");
      out.write("                border-radius: 10px;\r\n");
      out.write("                background-color: darkgrey;\r\n");
      out.write("                color: white;\r\n");
      out.write("                border: 0;\r\n");
      out.write("            }\r\n");
      out.write("            div{\r\n");
      out.write("                background-color: lightgray;\r\n");
      out.write("                padding: 10px;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("            }\r\n");
      out.write("            form{\r\n");
      out.write("                width: 700px;\r\n");
      out.write("                margin: 0 auto;\r\n");
      out.write("            }\r\n");
      out.write("            #ta{\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                padding:0;\r\n");
      out.write("                width: 700px;\r\n");
      out.write("                border-top: 1px solid #444444;\r\n");
      out.write("                border-collapse: collapse;\r\n");
      out.write("            }\r\n");
      out.write("            th, td {\r\n");
      out.write("                border-bottom: 1px solid #444444;\r\n");
      out.write("                padding: 10px;\r\n");
      out.write("            }\r\n");
      out.write("            #lab{\r\n");
      out.write("                background-color: lightgray;\r\n");
      out.write("                color: black;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                padding: 10px;   \r\n");
      out.write("            }\r\n");
      out.write("            #inp{\r\n");
      out.write("               padding: 10px;\r\n");
      out.write("               padding-left: 110px;\r\n");
      out.write("               padding-right: 100px;\r\n");
      out.write("            }\r\n");
      out.write("            tr td input{\r\n");
      out.write("                border-radius: 5px;\r\n");
      out.write("                height: 30px;\r\n");
      out.write("                width: 280px;\r\n");
      out.write("            }\r\n");
      out.write("            div select{\r\n");
      out.write("              height: 30px;\r\n");
      out.write("              border-radius: 5px;\r\n");
      out.write("              width: 80px;\r\n");
      out.write("              float: left;\r\n");
      out.write("              margin-left: 5px ;\r\n");
      out.write("           }\r\n");
      out.write("           h2{\r\n");
      out.write("               margin-left: 20px;\r\n");
      out.write("           }\r\n");
      out.write("           h3{\r\n");
      out.write("               float: left;\r\n");
      out.write("               margin-left: 20px;\r\n");
      out.write("           }\r\n");
      out.write("           #hh5{\r\n");
      out.write("               float:right;\r\n");
      out.write("               margin-bottom: 0;\r\n");
      out.write("               color: lightgray;\r\n");
      out.write("           }\r\n");
      out.write("           #agr{\r\n");
      out.write("               \r\n");
      out.write("               margin-left: 20px;\r\n");
      out.write("           }\r\n");
      out.write("           input::-webkit-input-placeholder { \r\n");
      out.write("                color: lightgray; \r\n");
      out.write("            }\r\n");
      out.write("            #t{\r\n");
      out.write("                border: 0;\r\n");
      out.write("            }\r\n");
      out.write("            #d{\r\n");
      out.write("                background-color: white;\r\n");
      out.write("            }\r\n");
      out.write("            #birth{\r\n");
      out.write("                background-color: white;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        \r\n");
      out.write("       ");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"UTF-8\">\n");
      out.write("\t\t<title>FUN-THING</title>\n");
      out.write("\t\t<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\n");
      out.write("\t\t<script src=\"https://canvasjs.com/assets/script/jquery-1.11.1.min.js\"></script>\n");
      out.write("        <script src=\"https://canvasjs.com/assets/script/jquery.canvasjs.min.js\"></script>\n");
      out.write("        <style>\n");
      out.write("            body{margin: auto; width: 100%;}\n");
      out.write("            /* #nav{margin: auto; width: 50%;} */\n");
      out.write("            #nav{background-color: rgb(199, 196, 196);}\n");
      out.write("            #nav_header{margin:auto; width:100%; height: 90px;}\n");
      out.write("            #nav_header ul li{float: left; width:7%; list-style-type: none; padding-right: 15px; padding-left: 15px; padding-top: 20px; line-height: auto;}\n");
      out.write("            #nav_header ul li button{width: 100%; height: 50px; background-color: gray; border-radius: 10px; border: 0px; font-size: 16px; font-weight: 600; color: white;}\n");
      out.write("\n");
      out.write("            \n");
      out.write("\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <header>\n");
      out.write("            <br>\n");
      out.write("            <h1 style=\"text-align: center;\">FUN-THING ADMIN</h1>\n");
      out.write("            <br>\n");
      out.write("            <div id=\"nav\" align=\"center\">\n");
      out.write("                <div id=\"nav_header\" align=\"center\">\n");
      out.write("                    <ul>\n");
      out.write("                        <li><button type=\"button\" onclick=\"productManage();\">상품관리</button></li>\n");
      out.write("                        <li><button type=\"button\" onclick=\"\">상품문의</button></li>\n");
      out.write("                        <li><button type=\"button\" onclick=\"orderManage();\">주문관리</button></li>\n");
      out.write("                        <li><button type=\"button\" onclick=\"\">매출관리</button></li>\n");
      out.write("                        <li><button type=\"button\" onclick=\"\">상품통계</button></li>\n");
      out.write("                        <li><button type=\"button\" onclick=\"memberManage();\">회원 관리</button></li>\n");
      out.write("                        <li><button type=\"button\" onclick=\"brandManage\">브랜드 관리</button></li>\n");
      out.write("                        <li><button type=\"button\" onclick=\"reviewManage\">리뷰관리</button></li>\n");
      out.write("                        <li><button type=\"button\" onclick=\"qnaManage();\">1:1문의 관리</button></li>\n");
      out.write("                        <li><button type=\"button\" onclick=\"pointManage();\">포인트</button></li>\n");
      out.write("                        <li><button type=\"button\" onclick=\"notice();\">공지사항 게시판</button></li>\n");
      out.write("\n");
      out.write("                        <!-- <li><button>캘린더 관리</button></li> -->\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <br>\n");
      out.write("        <hr clear=\"both\">\n");
      out.write("\t</body>\n");
      out.write("\t<script>\n");
      out.write("\t\tfunction productManage()\n");
      out.write("\t\t{\n");
      out.write("\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/admin/mainView?table=\" + \"PRODUCT\";\n");
      out.write("\t\t}\n");
      out.write("\t\t//상품 문의\n");
      out.write("\t\t\n");
      out.write("\t\tfunction orderManage()\n");
      out.write("\t\t{\n");
      out.write("\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/admin/orderInfo\";\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction memberManage()\n");
      out.write("\t\t{\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction brandManage()\n");
      out.write("\t\t{\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction reviewManage()\n");
      out.write("\t\t{\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction qnaManage()\n");
      out.write("\t\t{\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction pointManage()\n");
      out.write("\t\t{\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction notice()\n");
      out.write("\t\t{\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t</script>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <form method=\"post\" action=\"#\">\r\n");
      out.write("            <h2>회원정보수정</h2>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <h3>기본정보</h3>\r\n");
      out.write("            <br>\r\n");
      out.write("            <h5 id=\"hh5\">*은 반드시 적어야 하는 항목</h5>\r\n");
      out.write("            <table id=\"ta\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"lab\">\r\n");
      out.write("                        <label>*아이디</label>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td id=\"inp\">\r\n");
      out.write("                        <input type=\"text\" id=\"userid\" name=\"userid\" required placeholder=\"4글자 이상 12글자 이하 영문자(소문자)와 숫자\">\r\n");
      out.write("                        <input type=\"button\" id=\"ch\" value=\"중복확인\" style=\"width: 70px; background: darkgrey; color: white;\" onclick=\"openIdChk()\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"lab\">\r\n");
      out.write("                        <label>*비밀번호</label>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td id=\"inp\"> \r\n");
      out.write("                        <input type=\"password\" id=\"userpwd\" name=\"userpwd\" required placeholder=\"6글자 이상 18글자 이하 영문자(소문자)와 숫자\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"lab\"> \r\n");
      out.write("                        <label>*비밀번호 확인</label>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td id=\"inp\"> \r\n");
      out.write("                        <input type=\"password\" id=\"pwd_check\" name=\"pwd_check\" required>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"lab\">\r\n");
      out.write("                        <label>*이름</label>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td id=\"inp\">\r\n");
      out.write("                        <input type=\"text\" id=\"username\" name=\"username\" required placeholder=\"한글로 2글자 이상\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"lab\">\r\n");
      out.write("                        <label>*이메일</label>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td id=\"inp\">\r\n");
      out.write("                        <input type=\"email\" id=\"email\" name=\"eamil\" required>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"lab\">\r\n");
      out.write("                        <label>*휴대폰</label>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td id=\"inp\">\r\n");
      out.write("                        <input type=\"tel\" id=\"phone\" name=\"phone\" required placeholder=\"-제외 하고 입력\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"lab\">\r\n");
      out.write("                    <label>*생년월일</label>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td id=\"inp\">\r\n");
      out.write("                        <div id=\"birth\">\r\n");
      out.write("                            <select id=\"year\" required>\r\n");
      out.write("                                <option value=\"년\">년</option>\r\n");
      out.write("                                <option value=\"2020\">2020</option>\r\n");
      out.write("                                <option value=\"2019\">2019</option>\r\n");
      out.write("                                <option value=\"2018\">2018</option>\r\n");
      out.write("                                <option value=\"2017\">2017</option>\r\n");
      out.write("                                <option value=\"2016\">2016</option>\r\n");
      out.write("                                <option value=\"2015\">2015</option>\r\n");
      out.write("                                <option value=\"2014\">2014</option>\r\n");
      out.write("                                <option value=\"2013\">2013</option>\r\n");
      out.write("                                <option value=\"2012\">2012</option>\r\n");
      out.write("                                <option value=\"2011\">2011</option>\r\n");
      out.write("                                <option value=\"2010\">2010</option>\r\n");
      out.write("                                <option value=\"2009\">2009</option>\r\n");
      out.write("                                <option value=\"2008\">2008</option>\r\n");
      out.write("                                <option value=\"2007\">2007</option>\r\n");
      out.write("                                <option value=\"2006\">2006</option>\r\n");
      out.write("                                <option value=\"2005\">2005</option>\r\n");
      out.write("                                <option value=\"2004\">2004</option>\r\n");
      out.write("                                <option value=\"2003\">2003</option>\r\n");
      out.write("                                <option value=\"2002\">2002</option>\r\n");
      out.write("                                <option value=\"2001\">2001</option>\r\n");
      out.write("                                <option value=\"2000\">2000</option>\r\n");
      out.write("                                <option value=\"1999\">1999</option>\r\n");
      out.write("                                <option value=\"1998\">1998</option>\r\n");
      out.write("                                <option value=\"1997\">1997</option>\r\n");
      out.write("                                <option value=\"1996\">1996</option>\r\n");
      out.write("                                <option value=\"1995\">1995</option>\r\n");
      out.write("                                <option value=\"1994\">1994</option>\r\n");
      out.write("                                <option value=\"1993\">1993</option>\r\n");
      out.write("                                <option value=\"1992\">1992</option>\r\n");
      out.write("                                <option value=\"1991\">1991</option>\r\n");
      out.write("                                <option value=\"1990\">1990</option>\r\n");
      out.write("                                <option value=\"1989\">1989</option>\r\n");
      out.write("                                <option value=\"1988\">1988</option>\r\n");
      out.write("                                <option value=\"1987\">1987</option>\r\n");
      out.write("                                <option value=\"1986\">1986</option>\r\n");
      out.write("                                <option value=\"1985\">1985</option>\r\n");
      out.write("                                <option value=\"1984\">1984</option>\r\n");
      out.write("                                <option value=\"1983\">1983</option>\r\n");
      out.write("                                <option value=\"1982\">1982</option>\r\n");
      out.write("                                <option value=\"1981\">1981</option>\r\n");
      out.write("                                <option value=\"1980\">1980</option>\r\n");
      out.write("                                <option value=\"1979\">1979</option>\r\n");
      out.write("                                <option value=\"1978\">1978</option>\r\n");
      out.write("                                <option value=\"1977\">1977</option>\r\n");
      out.write("                                <option value=\"1976\">1976</option>\r\n");
      out.write("                                <option value=\"1975\">1975</option>\r\n");
      out.write("                                <option value=\"1974\">1974</option>\r\n");
      out.write("                                <option value=\"1973\">1973</option>\r\n");
      out.write("                                <option value=\"1972\">1972</option>\r\n");
      out.write("                                <option value=\"1971\">1971</option>\r\n");
      out.write("                                <option value=\"1970\">1970</option>\r\n");
      out.write("                                <option value=\"1969\">1969</option>\r\n");
      out.write("                                <option value=\"1968\">1968</option>\r\n");
      out.write("                                <option value=\"1967\">1967</option>\r\n");
      out.write("                                <option value=\"1966\">1966</option>\r\n");
      out.write("                                <option value=\"1965\">1965</option>\r\n");
      out.write("                                <option value=\"1964\">1964</option>\r\n");
      out.write("                                <option value=\"1963\">1963</option>\r\n");
      out.write("                                <option value=\"1962\">1962</option>\r\n");
      out.write("                                <option value=\"1961\">1961</option>\r\n");
      out.write("                                <option value=\"1960\">1960</option>\r\n");
      out.write("                                <option value=\"1959\">1959</option>\r\n");
      out.write("                                <option value=\"1958\">1958</option>\r\n");
      out.write("                                <option value=\"1957\">1957</option>\r\n");
      out.write("                                <option value=\"1956\">1956</option>\r\n");
      out.write("                                <option value=\"1955\">1955</option>\r\n");
      out.write("                                <option value=\"1954\">1954</option>\r\n");
      out.write("                                <option value=\"1953\">1953</option>\r\n");
      out.write("                                <option value=\"1952\">1952</option>\r\n");
      out.write("                                <option value=\"1951\">1951</option>\r\n");
      out.write("                                <option value=\"1950\">1950</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                            <select id=\"mon\" required>\r\n");
      out.write("                                <option value=\"월\">월</option>\r\n");
      out.write("                                <option value=\"1\">1</option>\r\n");
      out.write("                                <option value=\"2\">2</option>\r\n");
      out.write("                                <option value=\"3\">3</option>\r\n");
      out.write("                                <option value=\"4\">4</option>\r\n");
      out.write("                                <option value=\"5\">5</option>\r\n");
      out.write("                                <option value=\"6\">6</option>\r\n");
      out.write("                                <option value=\"7\">7</option>\r\n");
      out.write("                                <option value=\"8\">8</option>\r\n");
      out.write("                                <option value=\"9\">9</option>\r\n");
      out.write("                                <option value=\"10\">10</option>\r\n");
      out.write("                                <option value=\"11\">11</option>\r\n");
      out.write("                                <option value=\"12\">12</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                            <select id=\"day\" required>\r\n");
      out.write("                                <option value=\"일\">일</option>\r\n");
      out.write("                                <option value=\"1\">1</option>\r\n");
      out.write("                                <option value=\"2\">2</option>\r\n");
      out.write("                                <option value=\"3\">3</option>\r\n");
      out.write("                                <option value=\"4\">4</option>\r\n");
      out.write("                                <option value=\"5\">5</option>\r\n");
      out.write("                                <option value=\"6\">6</option>\r\n");
      out.write("                                <option value=\"7\">7</option>\r\n");
      out.write("                                <option value=\"8\">8</option>\r\n");
      out.write("                                <option value=\"9\">9</option>\r\n");
      out.write("                                <option value=\"10\">10</option>\r\n");
      out.write("                                <option value=\"11\">11</option>\r\n");
      out.write("                                <option value=\"12\">12</option>\r\n");
      out.write("                                <option value=\"13\">13</option>\r\n");
      out.write("                                <option value=\"14\">14</option>\r\n");
      out.write("                                <option value=\"15\">15</option>\r\n");
      out.write("                                <option value=\"16\">16</option>\r\n");
      out.write("                                <option value=\"17\">17</option>\r\n");
      out.write("                                <option value=\"18\">18</option>\r\n");
      out.write("                                <option value=\"19\">19</option>\r\n");
      out.write("                                <option value=\"20\">20</option>\r\n");
      out.write("                                <option value=\"21\">21</option>\r\n");
      out.write("                                <option value=\"22\">22</option>\r\n");
      out.write("                                <option value=\"23\">23</option>\r\n");
      out.write("                                <option value=\"24\">24</option>\r\n");
      out.write("                                <option value=\"25\">25</option>\r\n");
      out.write("                                <option value=\"26\">26</option>\r\n");
      out.write("                                <option value=\"27\">27</option>\r\n");
      out.write("                                <option value=\"28\">28</option>\r\n");
      out.write("                                <option value=\"29\">29</option>\r\n");
      out.write("                                <option value=\"30\">30</option>\r\n");
      out.write("                                <option value=\"31\">31</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"lab\">\r\n");
      out.write("                        <label>추천인</label>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td id=\"inp\">\r\n");
      out.write("                        <input type=\"text\" id=\"reference\" name=\"reference\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <br>\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"d\" style=\"text-align: center;\">\r\n");
      out.write("                <input type=\"submit\" value=\"수정\" id=\"submit_btn\" style=\"width: 90px; height: 40px; border: 0; color: white; background: darkgrey; border-radius: 7px;\" onclick=\"insertCheck()\">\r\n");
      out.write("                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;\r\n");
      out.write("                <input type=\"button\" value=\"취소\" id=\"cancel\" onclick=cancle(); style=\"width: 90px; height: 40px; border: 0; color: black; background-color: lightgray; border-radius: 7px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\t</body>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction productManage()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tlocation.href=\"views/admin/productManage.jsp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("                $('ipnut[type=checkbox]').click(function(){\r\n");
      out.write("                    console.log($(this).prop(\"checked\"));\r\n");
      out.write("                });\r\n");
      out.write("                $(\"#checkAll\").click(function(){\r\n");
      out.write("                    var bool = $(\"#checkAll\").prop(\"checked\");\r\n");
      out.write("                    $(\".infoBox\").prop(\"checked\",bool);\r\n");
      out.write("                });\r\n");
      out.write("                $(\"#userid\").change(function(){\r\n");
      out.write("                    var value = $(\"#userid\").val();\r\n");
      out.write("                    var reg = /^[a-z0-9]{4,12}$/;\r\n");
      out.write("                    if(!reg.test(value)){\r\n");
      out.write("                        alert(\"영문자와 숫자로 4글자 이상 12글자 이하여야 합니다.\");\r\n");
      out.write("                        $(\"#userid\").focus().val('');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                $(\"#userpwd\").change(function(){\r\n");
      out.write("                    var value = $(\"#userpwd\").val();\r\n");
      out.write("                    var reg = /^[a-z0-9]{6,18}$/;\r\n");
      out.write("                    if(!reg.test(value)){\r\n");
      out.write("                        alert(\"영문자와 숫자로 6글자 이상 12글자 이하여야 합니다.\");\r\n");
      out.write("                        $(\"#userpwd\").focus().val('');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                $(\"#pwd_check\").change(function(){\r\n");
      out.write("                    var pw1 = $(\"#userpwd\").val();\r\n");
      out.write("                    var pw2 = $(\"#pwd_check\").val();\r\n");
      out.write("                    \r\n");
      out.write("                    if(pw1 == pw2){\r\n");
      out.write("                        $(\"#pwd_check\").val();\r\n");
      out.write("                    }else{\r\n");
      out.write("                        alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("                        $(\"#pwd_check\").focus().val('');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                $(\"#username\").change(function(){\r\n");
      out.write("                    var value = $(\"#username\").val();\r\n");
      out.write("                    var reg = /^[가-힣]{2,4}$/;\r\n");
      out.write("                    \r\n");
      out.write("                    if(!reg.test(value)){\r\n");
      out.write("                        alert(\"한글로 2글자 이상 입력해주세요.\");\r\n");
      out.write("                        $(\"#username\").focus().val('');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                $(\"#phone\").change(function(){\r\n");
      out.write("                    var value = $(\"#phone\").val();\r\n");
      out.write("                    var reg = /^[0-9]{11}$/;\r\n");
      out.write("                    \r\n");
      out.write("                    if(!reg.test(value)){\r\n");
      out.write("                        alert(\"-를 제외한 숫자만을 입력해 주세요.\");\r\n");
      out.write("                        $(\"#phone\").focus().val('');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
